import type * as Wire from '../shared/api/generated/commands';
import { type Label } from '../profiles/schema';
export type LegacyReviewData = Wire.LegacyBackupPreview;
/** Settings groups a Throne backup can restore, as the engine contract names them. */
export type SettingsScope = keyof NonNullable<LegacyReviewData['scopes']['settings']>;
/** The groups in review order; the check below fails to compile when the contract adds one. */
export const settingsScopes = [
  'appearance',
  'testing',
  'logging',
  'geodata',
  'warp',
  'network',
  'subscriptions',
  'inbound',
  'system',
  'presets',
  'intercept',
  'tun',
  'core',
  'hotkeys',
] as const satisfies readonly SettingsScope[];
const everyScopeListed: Exclude<SettingsScope, (typeof settingsScopes)[number]> extends never ? true : never =
  true;
void everyScopeListed;

export const messageKeys = {
  iconsScope: 'backups.icons_scope',
  iconsHint: 'backups.icons_hint',
  iconsPlanned: 'backups.icons_planned',
  trafficPlanned: 'backups.traffic_planned',
  legacy_icons_part_missing: 'backups.icons_part_missing',
  legacy_icons_empty: 'backups.icons_empty',
  legacy_icons_invalid: 'backups.icons_invalid',
  legacy_icons_unused: 'backups.icons_unused',
  vpnBindingChoice: 'backups.vpn_confirmation_codes_dd0a66a',
  vpnBindingUnchosen: 'backups.choose_how_to_import_f43f58a',
  vpnBindingAuto: 'backups.link_otp_for_supported_login_prompts_57b776d',
  vpnBindingManual: 'backups.enter_codes_manually_398e478',
  vpnBindingHint: 'backups.linked_entries_can_supply_codes_to_supported_vpn_4509e5e',
  vpnBindingManualHint: 'backups.manual_entry_is_available_only_where_the_saved_v_dbb9d2b',
  vpnBindingManualUnavailable: 'backups.requires_a_linked_otp_entry_e2c0a20',
  vpnBindingsPlanned: 'backups.vpn_links_to_add_3f62eb3',
  legacy_vpn_system_unsupported: 'backups.the_saved_vpn_uses_system_interfaces_that_this_i_44512ea',
  legacy_vpn_auth_unsupported: 'backups.this_vpn_authentication_method_needs_additional__0bd088e',
  legacy_vpn_dns_override_unsupported: 'backups.the_saved_custom_dns_overrides_the_vpn_policy_th_41011a5',
  legacy_vpn_graph_unsupported: 'backups.this_vpn_policy_cannot_yet_be_preserved_inside_t_9c797c5',
  legacy_vpn_bindings_choice_required: 'backups.choose_how_to_handle_vpn_confirmation_codes_befo_1d7dec6',
  legacy_vpn_bindings_require_otp: 'backups.select_otp_entries_from_this_backup_to_import_th_3713f66',
  legacy_vpn_binding_missing: 'backups.the_vpn_refers_to_an_otp_entry_that_is_missing_o_1794052',
  legacy_vpn_binding_required: 'backups.this_vpn_contains_an_otp_template_and_needs_its__0e860e1',
  legacy_vpn_binding_unsupported: 'backups.the_saved_otp_template_cannot_be_used_with_the_s_2dae27c',
  legacy_vpn_bindings_auto_start: 'backups.legacy_vpn_bindings_auto_start',
  vpnBindingBeforeStart: 'backups.vpn_binding_before_start',
  vpnBindingAfterPrompt: 'backups.vpn_binding_after_prompt',
  legacy_vpn_bindings_auto_live: 'backups.the_original_otp_entry_will_be_linked_for_suppor_9c10a08',
  legacy_vpn_bindings_manual: 'backups.this_profile_will_use_manual_confirmation_code_e_ae62e86',
  legacy_vpn_policy_preserved: 'backups.the_vpn_routing_and_dns_policy_will_be_preserved_d1f0732',
  settings_appearance: 'backups.supported_interface_settings_df3536c',
  settings_testing: 'backups.supported_test_settings_76b4f01',
  settings_logging: 'backups.logging_and_statistics',
  settings_network: 'backups.network_request_settings_e87c394',
  settings_subscriptions: 'backups.subscription_update_settings_1a08e35',
  networkImportHint: 'backups.import_changes_how_future_requests_use_the_proxy_c9c8378',
  subscriptionImportHint: 'backups.the_selected_update_interval_also_applies_to_gro_b6886e5',
  legacy_network_value_unsupported: 'backups.a_saved_network_or_subscription_value_has_an_uns_5fff7c1',
  legacy_network_default_user_agent: 'backups.the_empty_old_user_agent_will_use_the_standard_t_1414096',
  legacy_network_proxy_enabled: 'backups.future_requests_will_use_the_active_application__844a5d0',
  legacy_network_insecure_enabled: 'backups.the_saved_settings_disable_certificate_verificat_236ce25',
  legacy_subscription_interval_disabled: 'backups.throne_treats_this_saved_interval_as_disabled_au_fee65fb',
  legacy_subscription_recreate: 'backups.subscription_recreate_notice',
  legacy_subscription_reconcile: 'backups.updates_will_retain_matching_profiles_and_remove_933d566',
  legacy_subscription_clear_all_unsupported:
    'backups.the_old_setting_clears_all_eligible_profiles_bef_711cf7f',
  legacy_subscription_hwid_enabled: 'backups.subscription_requests_will_send_device_identific_e9779c0',
  legacy_subscription_stopping_enabled: 'backups.updates_will_be_allowed_to_stop_an_affected_acti_fce5427',
  settings_warp: 'backups.warp_settings_and_keys_88b9786',
  warpHint: 'backups.import_replaces_the_saved_warp_settings_includin_0ccb425',
  legacy_warp_bundle_incomplete: 'backups.the_warp_identity_is_incomplete_export_all_six_w_624e807',
  legacy_warp_value_unsupported: 'backups.a_saved_warp_key_endpoint_address_or_reserved_va_e447bdd',
  legacy_warp_enabled: 'backups.warp_will_be_enabled_after_the_selected_server_o_16e3fbc',
  settings_geodata: 'backups.geoip_geosite_sources_and_history_a66766a',
  settings_inbound: 'backups.settings_inbound',
  settings_system: 'backups.settings_system',
  settings_presets: 'backups.settings_presets',
  settings_intercept: 'backups.settings_intercept',
  settings_tun: 'backups.settings_tun',
  settings_core: 'backups.settings_core',
  settings_hotkeys: 'backups.settings_hotkeys',
  legacy_hotkeys_duplicate: 'backups.legacy_hotkeys_duplicate',
  legacy_hotkeys_registered: 'backups.legacy_hotkeys_registered',
  runtimeImportHint: 'backups.runtime_import_hint',
  systemImportHint: 'backups.system_import_hint',
  legacy_inbound_auth_enabled: 'backups.legacy_inbound_auth_enabled',
  legacy_inbound_auth_incomplete: 'backups.legacy_inbound_auth_incomplete',
  legacy_inbound_lan_listen: 'backups.legacy_inbound_lan_listen',
  legacy_inbound_custom_listeners: 'backups.legacy_inbound_custom_listeners',
  legacy_system_url_scheme_enabled: 'backups.legacy_system_url_scheme_enabled',
  legacy_system_tray_disabled: 'backups.legacy_system_tray_disabled',
  legacy_system_custom_icons_deferred: 'backups.legacy_system_custom_icons_deferred',
  legacy_intercept_lan_listen: 'backups.legacy_intercept_lan_listen',
  legacy_tun_permission_disabled: 'backups.legacy_tun_permission_disabled',
  legacy_core_ntp_default_port: 'backups.legacy_core_ntp_default_port',
  legacy_core_clash_api_enabled: 'backups.legacy_core_clash_api_enabled',
  legacy_core_api_enabled: 'backups.legacy_core_api_enabled',
  legacy_core_route_interval_disabled: 'backups.legacy_core_route_interval_disabled',
  legacy_core_clash_secret_required: 'backups.legacy_core_clash_secret_required',
  geodataHint: 'backups.import_replaces_the_selected_source_urls_and_rec_a7ca0c2',
  historyGeoip: 'backups.recent_geoip_source_urls_fa6d248',
  historyGeosite: 'backups.recent_geosite_source_urls_0d5cbc0',
  legacy_geodata_url_unsupported: 'backups.a_geodata_url_is_unsupported_use_https_addresses_fd93f33',
  legacy_geodata_default_source: 'backups.an_explicitly_empty_source_uses_the_same_default_403afc3',
  settingsScopeHint: 'backups.the_listed_settings_replace_their_current_values_76ea3a4',
  settingsPlanned: 'backups.settings_to_replace_3a53b28',
  remainingSettings: 'backups.settings_not_imported_2d21a62',
  legacy_settings_part_missing: 'backups.the_settings_section_was_not_selected_in_this_th_d8ae046',
  legacy_settings_empty: 'backups.the_selected_categories_contain_no_supported_sav_b804b22',
  legacy_settings_structure: 'backups.a_supported_setting_has_an_invalid_stored_type_o_02c5a12',
  legacy_settings_value_invalid: 'backups.a_supported_setting_has_an_invalid_value_this_ca_920d8b6',
  legacy_settings_duplicate: 'backups.a_supported_setting_occurs_more_than_once_in_thi_63a262f',
  legacy_settings_language_unsupported: 'backups.this_saved_language_cannot_be_mapped_exactly_lea_8d128e4',
  legacy_settings_speed_mode_unsupported: 'backups.this_saved_test_mode_is_not_supported_leave_the__19546f4',
  legacy_settings_limit: 'backups.the_saved_settings_exceed_the_supported_limits_f373fe8',
  legacy_settings_sort_unsupported: 'backups.legacy_settings_sort_unsupported',
  legacy_settings_sort_default: 'backups.legacy_settings_sort_default',
  legacy_settings_retention_minimum: 'backups.legacy_settings_retention_minimum',
  legacy_settings_regex_engine: 'backups.legacy_settings_regex_engine',
  legacy_settings_regex_unsupported: 'backups.legacy_settings_regex_unsupported',
  legacy_settings_partial: 'backups.only_the_listed_compatible_settings_in_this_cate_91c2f90',
  otpScope: 'backups.authenticator_entries_otp_8bd5380',
  otpScopeHint: 'backups.otp_entries_are_added_with_new_identifiers_prese_cb11a3d',
  otpPlanned: 'backups.otp_entries_to_add_05f0b86',
  legacy_otp_parts_required: 'backups.the_otp_section_was_not_selected_in_this_throne__ef14b96',
  legacy_otp_empty: 'backups.the_selected_otp_section_contains_no_entries_3042a65',
  legacy_otp_structure: 'backups.a_saved_otp_field_has_an_invalid_type_or_format_f8bc684',
  legacy_otp_field_unsupported: 'backups.a_saved_otp_field_is_not_supported_by_this_impor_f0b76d4',
  legacy_otp_id_invalid: 'backups.the_otp_section_has_invalid_or_duplicate_identif_7079c4c',
  legacy_otp_algorithm_invalid: 'backups.an_otp_entry_uses_an_unsupported_algorithm_a83104d',
  legacy_otp_type_invalid: 'backups.an_otp_entry_has_an_unsupported_type_d0e157b',
  legacy_otp_digits_invalid: 'backups.an_otp_entry_has_an_invalid_number_of_digits_a3b1527',
  legacy_otp_period_invalid: 'backups.an_otp_entry_has_an_invalid_time_period_4a30694',
  legacy_otp_counter_invalid: 'backups.an_otp_entry_has_an_invalid_counter_b185d59',
  legacy_otp_label_invalid: 'backups.an_otp_name_or_issuer_exceeds_the_supported_limi_b86eb90',
  legacy_otp_secret_invalid: 'backups.an_otp_entry_has_an_invalid_base32_secret_f3e939e',
  legacy_otp_limit: 'backups.the_otp_section_exceeds_the_supported_entry_or_s_7d0286a',
  legacy_otp_order_default: 'backups.this_older_entry_had_no_saved_position_its_sourc_bdff935',
  legacy_otp_timestamps_deferred: 'backups.the_old_creation_and_modification_dates_remain_i_50c17b2',
  legacy_otp_bindings_deferred: 'backups.some_otp_links_are_excluded_from_this_import_the_d12bed9',
  selectorChoice: 'backups.import_the_last_saved_selector_members_new_subsc_958c4f6',
  selectorHint: 'backups.automatic_server_selection_and_availability_chec_c0f5744',
  selectorMembers: 'backups.members_cb2ec4f',
  selectorPinned: 'backups.preferred_server_saved_d7f0334',
  legacy_selector_snapshot_choice_required:
    'backups.choose_whether_to_import_the_last_saved_selector_98be059',
  legacy_selector_snapshot_empty: 'backups.this_selector_has_no_saved_member_list_connect_i_623622c',
  legacy_selector_snapshot_limit: 'backups.the_saved_selector_lists_exceed_the_supported_li_174718b',
  legacy_selector_reference_missing: 'backups.a_saved_selector_member_is_missing_from_the_back_c004c2d',
  legacy_selector_reference_invalid: 'backups.a_saved_selector_list_contains_invalid_or_duplic_5eb76f3',
  legacy_selector_member_unsupported: 'backups.a_saved_member_uses_a_profile_type_that_this_sel_5ef5e91',
  legacy_selector_pin_outside_snapshot: 'backups.the_preferred_server_is_outside_the_saved_member_0619569',
  legacy_selector_field_unsupported: 'backups.a_saved_selector_parameter_is_not_supported_by_t_65c1d70',
  legacy_import_requires_warp: 'backups.warp_import_dependency',
  legacy_selector_warp_unsupported: 'backups.the_saved_selector_uses_a_warp_wrapper_whose_imp_d818a67',
  legacy_selector_structure: 'backups.a_saved_selector_field_has_an_invalid_type_or_fo_bb0e07a',
  legacy_selector_group_missing: 'backups.the_group_containing_this_selector_is_missing_fr_d0839c5',
  legacy_selector_settings_invalid: 'backups.the_source_selector_settings_contain_invalid_or__129ad60',
  legacy_selector_url_invalid: 'backups.a_saved_availability_check_url_is_invalid_or_uns_ebd89a4',
  legacy_selector_value_unsupported: 'backups.a_saved_selector_value_is_outside_the_supported__c659d80',
  legacy_selector_type_unsupported: 'backups.the_stored_profile_type_does_not_match_its_selec_60df845',
  legacy_selector_history_limit: 'backups.the_saved_selector_history_exceeds_the_supported_1b097dd',
  legacy_selector_fixed_snapshot: 'backups.this_selector_will_use_its_last_saved_member_lis_0f32b58',
  legacy_selector_history_deferred: 'backups.previous_selector_measurements_and_history_remai_2096c83',
  legacy_selector_source_group_missing: 'backups.the_formerly_tracked_group_is_absent_the_saved_m_f9092bc',
  selectScope: 'backups.select_an_available_section_to_import_f83195b',
  legacy_import_select_scope: 'backups.no_sections_are_selected_for_import_84b7b6b',
  routeValidation: 'backups.before_applying_a_preset_the_app_checks_its_conf_c5f4508',
  legacy_route_empty_rule_omitted: 'backups.an_empty_rule_placeholder_was_omitted_as_in_thro_09b26f0',
  legacy_route_inactive_rules_omitted: 'backups.stored_form_rules_do_not_add_traffic_routes_to_t_09780dc',
  legacy_route_tun_guarded: 'backups.this_imported_preset_currently_supports_local_or_19babf5',
  legacy_dns_transport_unsupported: 'backups.this_dns_server_type_needs_additional_conversion_3af0d17',
  legacy_dns_reference_cycle: 'backups.the_saved_dns_servers_have_a_resolver_reference__6e8269b',
  legacy_column_type: 'backups.a_source_database_value_has_an_unsupported_type_4eb921f',
  legacy_database_missing: 'backups.this_backup_has_no_database_to_import_d3af8cb',
  chooseScopes: 'backups.sections_to_add_eaaad02',
  profileScope: 'backups.profiles_and_groups_712d27f',
  routeScope: 'backups.routing_presets_with_their_saved_dns_2d58d6b',
  routeScopeHint: 'backups.presets_are_added_separately_your_active_preset__b365988',
  routePlanned: 'backups.routing_presets_to_add_1396f26',
  routeRequirements: 'backups.these_presets_can_be_imported_now_before_applyin_feafbaa',
  settingsGeneral: 'backups.general_application_settings_78e788a',
  legacy_settings_general_deferred: 'backups.general_application_settings_stay_in_the_backup__93f8551',
  legacy_routes_require_profiles: 'backups.these_routes_reference_profiles_from_the_same_ba_772d6cd',
  legacy_route_parts_required: 'backups.the_backup_must_include_both_routing_and_setting_638baf3',
  legacy_dns_generated_settings_invalid: 'backups.the_saved_dns_settings_contain_invalid_or_confli_e98dec4',
  legacy_dns_generated_limit: 'backups.the_saved_dns_settings_exceed_the_supported_limi_8283279',
  legacy_dns_generated_mode_required: 'backups.the_saved_settings_do_not_select_generated_dns_6525009',
  legacy_dns_generated_dependency_unsupported:
    'backups.this_dns_policy_depends_on_fake_ip_system_hosts__0dcecbc',
  legacy_dns_address_unsupported: 'backups.a_saved_dns_server_address_cannot_be_transferred_0639765',
  legacy_dns_remote_transport_unsupported: 'backups.this_remote_dns_transport_depends_on_the_selecte_bfefdb7',
  legacy_dns_bootstrap_hostname_unsupported:
    'backups.the_saved_bootstrap_dns_uses_a_hostname_without__b27c70e',
  legacy_dns_strategy_alias_conflict: 'backups.the_backup_contains_conflicting_old_and_new_dns__bc8fa3e',
  legacy_dns_predefined_unsupported: 'backups.a_saved_dns_override_has_an_unsupported_address__d8d3ddf',
  legacy_dns_selector_unsupported: 'backups.a_condition_used_to_generate_dns_rules_cannot_be_8769bc1',
  legacy_dns_generated_local_modes: 'backups.dns_was_generated_from_the_saved_settings_for_lo_4b890d5',
  legacy_dns_xray_remote_upgrade: 'backups.dns_xray_remote_upgrade',
  legacy_dns_selector_projection: 'backups.dns_follows_the_saved_domain_conditions_in_the_s_6696e50',
  legacy_dns_optimistic_suppressed: 'backups.optimistic_dns_caching_is_inactive_because_cachi_afecb86',
  legacy_route_runtime_unsupported: 'backups.the_saved_routes_depend_on_system_or_global_netw_460ef9a',
  legacy_route_remote_updates: 'backups.legacy_route_remote_updates',
  legacy_route_raw_verbatim: 'backups.legacy_route_raw_verbatim',
  legacy_route_source_unsupported: 'backups.remote_automatically_updated_or_protected_routin_7046e1f',
  legacy_route_ruleset_unsupported: 'backups.this_routing_preset_uses_rule_set_resources_whos_35345b2',
  legacy_route_reference_missing: 'backups.a_route_references_a_profile_or_dns_server_missi_e029eed',
  legacy_route_endpoint_unsupported: 'backups.legacy_route_endpoint_unsupported',
  legacy_route_endpoint_rule_added: 'backups.legacy_route_endpoint_rule_added',
  legacy_route_endpoint_rule_omitted: 'backups.legacy_route_endpoint_rule_omitted',
  legacy_route_endpoint_tunnel_dns: 'backups.legacy_route_endpoint_tunnel_dns',
  legacy_route_inbound_unsupported: 'backups.legacy_route_inbound_unsupported',
  legacy_route_inbound_unknown: 'backups.legacy_route_inbound_unknown',
  legacy_route_inbound_requires_settings: 'backups.legacy_route_inbound_requires_settings',
  legacy_profile_resource_required: 'backups.legacy_profile_resource_required',
  legacy_profile_resource_unsupported: 'backups.legacy_profile_resource_unsupported',
  legacy_profile_initial_path_omitted: 'backups.legacy_profile_initial_path_omitted',
  legacy_tailscale_state_omitted: 'backups.legacy_tailscale_state_omitted',
  legacy_profile_skipped: 'backups.legacy_profile_skipped',
  legacy_profile_group_skipped: 'backups.legacy_profile_group_skipped',
  legacy_group_skipped: 'backups.legacy_group_skipped',
  legacy_group_proxy_skipped: 'backups.legacy_group_proxy_skipped',
  resourcesRouteGroup: 'backups.resources_route_group',
  resourcesProfileGroup: 'backups.resources_profile_group',
  legacy_route_field_unsupported: 'backups.a_routing_or_dns_parameter_cannot_be_preserved_b_7885c0b',
  legacy_route_limit: 'backups.routing_is_empty_or_exceeds_the_supported_preset_0397110',
  legacy_route_type_unsupported: 'backups.this_saved_rule_type_needs_additional_conversion_907f80d',
  legacy_route_action_unsupported: 'backups.this_routing_or_dns_action_needs_additional_conv_fea2313',
  legacy_route_structure: 'backups.a_saved_routing_value_has_an_invalid_type_or_for_8c80e40',
  legacy_route_json_invalid: 'backups.the_saved_routing_json_is_invalid_958e37b',
  legacy_route_target_unsupported: 'backups.this_saved_routing_destination_cannot_be_mapped__4cf237b',
  legacy_dns_invalid: 'backups.the_saved_dns_configuration_is_invalid_or_unsupp_a673369',
  legacy_dns_reference_missing: 'backups.a_dns_reference_does_not_identify_a_server_in_th_2143896',
  legacy_route_settings_invalid: 'backups.the_source_routing_settings_contain_invalid_or_c_203dcdf',
  legacy_route_selected_missing: 'backups.the_old_active_routing_preset_is_absent_your_cur_3ae4b21',
  legacy_route_empty_placeholder: 'backups.an_empty_rule_placeholder_was_omitted_as_in_thro_09b26f0',
  route: 'backups.routing_preset_56e04af',
  title: 'backups.import_profiles_from_throne_1f2b2c0',
  source: 'backups.in_the_backup_7e07577',
  profiles: 'backups.profiles_a0a505c',
  groups: 'backups.groups_6af1c99',
  scope: 'backups.profiles_and_groups_are_added_to_your_current_li_a2f57b1',
  network: 'backups.this_mode_uses_your_current_client_routing_and_s_1831c8c',
  deferred: 'backups.separate_backup_sections_are_not_imported_in_thi_b37ddce',
  routing: 'backups.routing_3247b97',
  settings: 'backups.settings_including_client_dns_418c07c',
  otp: 'backups.otp_entries_8c46a29',
  icons: 'backups.icons_50bed94',
  unsupported: 'backups.some_entries_need_additional_conversion_this_imp_6c4b81e',
  notes: 'backups.conversion_notes_30aa9b6',
  more: 'backups.more_notes_16c397b',
  profile: 'backups.profile_410ec9f',
  group: 'backups.group_aaf618a',
  database: 'backups.backup_f007fa6',
  noProfiles: 'backups.this_backup_has_no_selected_profile_section_to_i_a4016ad',
  incompatible: 'backups.the_imported_sections_conflict_with_the_current__91f5343',
  conversion: 'backups.parameters_or_references_require_conversion_b0b5320',
  legacy_profile_order_deduplicated: 'backups.repeated_entries_in_the_saved_display_order_were_945ee73',
  legacy_profile_order_completed: 'backups.profiles_missing_from_the_saved_display_order_we_6c14ebb',
  legacy_group_order_completed: 'backups.the_group_had_no_saved_position_and_was_placed_a_a4cb352',
  legacy_subscription_manual_review: 'backups.automatic_updates_are_off_check_the_imported_ser_85448e9',
  legacy_subscription_user_agent_review: 'backups.the_backup_has_no_subscription_user_agent_check__39193d9',
  legacy_subscription_transport_review: 'backups.check_hwid_authentication_and_certificate_settin_8016123',
  legacy_group_archive_deferred: 'backups.the_old_archive_flag_is_not_imported_this_group__0987097',
  legacy_group_info_deferred: 'backups.the_old_group_description_is_not_imported_edaf68a',
  legacy_profile_name_generated: 'backups.a_name_was_generated_for_the_unnamed_profile_165a54a',
  legacy_selection_informational: 'backups.the_current_profile_selection_is_kept_2c972b3',
  legacy_selection_missing: 'backups.the_old_selected_profile_is_missing_the_current__f011d5d',
  legacy_current_network_settings_retained: 'backups.the_current_client_network_settings_are_used_095b2f2',
  legacy_settings_deferred: 'backups.general_settings_including_client_dns_remain_in__e110985',
  legacy_routing_deferred: 'backups.general_routing_profiles_remain_in_the_source_ba_65eafef',
  legacy_otp_deferred: 'backups.otp_entries_remain_in_the_source_backup_27932a6',
  legacy_profile_metrics_deferred: 'backups.previous_measurements_and_traffic_counters_are_n_c2a0eee',
  legacy_group_layout_deferred: 'backups.old_table_and_layout_preferences_are_not_importe_998fc24',
  legacy_other_tables_deferred: 'backups.additional_database_sections_remain_in_the_sourc_e8c37da',
  legacy_unknown_columns_deferred: 'backups.unknown_fields_of_groups_or_profiles_from_a_newe_644b19b',
  legacy_backup_unknown_files_deferred: 'backups.additional_files_of_the_backup_are_not_imported_bb62991',
  legacy_profile_autoselector_unsupported: 'backups.this_old_automatic_selector_is_not_supported_by__c2034cf',
  legacy_profile_external_core_unsupported:
    'backups.external_core_profiles_are_not_supported_by_the__ab0d9a0',
  legacy_external_launch_review: 'backups.the_external_program_and_its_arguments_will_be_c_d99fb47',
  legacy_external_runtime_subset: 'backups.this_external_core_profile_supports_a_standalone_111725f',
  externalPlanned: 'backups.external_core_profiles_to_add_e36853d',
  legacy_external_output_enabled: 'backups.output_from_the_external_program_remains_enabled_d20002e',
  legacy_external_platform_unsupported: 'backups.importing_external_core_profiles_is_currently_su_1a59f90',
  legacy_external_address_unsupported: 'backups.the_external_core_must_listen_on_127_0_0_1_the_s_833f3e4',
  legacy_external_port_invalid: 'backups.external_core_port_invalid',
  legacy_external_path_invalid: 'backups.the_external_program_needs_a_valid_absolute_linu_59d7b7e',
  legacy_external_name_invalid: 'backups.the_external_core_name_exceeds_the_supported_len_e12eb6c',
  legacy_external_args_invalid: 'backups.external_core_arguments_invalid',
  legacy_external_config_invalid: 'backups.external_core_configuration_invalid',
  legacy_wireguard_field_unsupported: 'backups.this_wireguard_profile_has_parameters_that_the_i_7f9c6f4',
  legacy_wireguard_alias_conflict: 'backups.this_wireguard_profile_contains_conflicting_old__b04d0de',
  legacy_wireguard_key_invalid: 'backups.a_wireguard_key_has_an_invalid_format_cc22f3e',
  legacy_wireguard_prefix_invalid: 'backups.a_wireguard_address_or_allowed_network_is_invali_9fb4e4e',
  legacy_wireguard_duplicate_peer: 'backups.this_wireguard_profile_contains_peers_with_the_s_ee6f337',
  legacy_wireguard_peer_invalid: 'backups.a_wireguard_peer_has_an_invalid_address_or_port_4b75640',
  legacy_wireguard_peer_limit: 'backups.wireguard_peer_count',
  legacy_wireguard_reserved_invalid: 'backups.wireguard_reserved_bytes_must_contain_three_numb_68bf80e',
  legacy_wireguard_range_invalid: 'backups.an_amneziawg_value_or_range_is_invalid_4caca9c',
  legacy_wireguard_duration_invalid: 'backups.a_wireguard_duration_is_invalid_3eebcd3',
  legacy_wireguard_signature_unsupported: 'backups.an_amneziawg_signature_cannot_be_preserved_in_it_3ff086c',
  legacy_wireguard_structure: 'backups.this_wireguard_profile_has_invalid_field_types_54f1a85',
  legacy_wireguard_value_unsupported: 'backups.a_wireguard_parameter_is_outside_the_supported_r_e4e6dd7',
  legacy_wireguard_type_unsupported: 'backups.the_stored_protocol_does_not_match_the_wireguard_211c3ca',
  legacy_profile_wireguard_unsupported: 'backups.this_warp_profile_needs_additional_account_and_w_633b3d9',
  legacy_profile_field_unsupported: 'backups.the_profile_has_parameters_that_this_importer_ca_6414692',
  legacy_profile_external_resource: 'backups.the_profile_depends_on_files_outside_the_backup_c455a26',
  legacy_chain_cycle: 'backups.the_chain_contains_a_reference_cycle_e2d395d',
  legacy_chain_reference_missing: 'backups.a_member_of_the_chain_is_missing_from_the_backup_a5935a1',
  legacy_chain_too_long: 'backups.the_chain_exceeds_the_supported_number_of_hops_b37ddce',
} satisfies Record<string, Label>;
