// Generated from desktop/locales/languages.json and each native.json.
#[rustfmt::skip]
pub const CATALOGS: &[(&str, &str)] = &[
    ("en", include_str!("../../locales/en/native.json")),
    ("ru", include_str!("../../locales/ru/native.json")),
];
#[derive(Clone, Copy)]
#[rustfmt::skip]
pub enum TextKey {
    AllTrafficThroughProxy0c33426,
    ApplySavedChanges68db303,
    AutoSelect,
    BackupFilter,
    BackupOpenFilter,
    BlockAdvertisements7303abe,
    ChangePolicyInRoutingSettings84336e9,
    ChinaB2aa98d,
    ChooseCoreExecutable087bad5,
    ChoosePolicyResource,
    ConnectA27ba0c,
    ConnectToServer87401c4,
    Connected8582d18,
    ConnectingToVpnE25b29b,
    CoreUnavailable9f988f6,
    CouldNotChangeTheConnectionCheckTheProfilDc86529,
    CouldNotSaveRoutingTryAgainInRoutingSettAc73861,
    CouldNotSaveThisSettingCheckTheAdblockWa9daf1aa,
    DirectConnection17b0c96,
    Disconnect2d5128c,
    Disconnected47d3ebf,
    Favorites3fcf8bf,
    FullConfigurationControlsRoutingF940dbc,
    Groups6af1c99,
    Iran0aec67d,
    LoadProfile6dd7d64,
    NoServersDa4c36b,
    NotificationConnectionLost,
    NotificationConnectionLostBody,
    NotificationReconnecting,
    NotificationReconnectingBody,
    NotificationRestored,
    NotificationRestoredBody,
    NotificationSubscriptionsChanged,
    NotificationSubscriptionsChangedBody,
    OpenBackup53325a0,
    OpenThronium5ce46db,
    OtpCodes83b6c30,
    Personal09c5ff5,
    Quit9f9f8cf,
    ReconnectingAef685e,
    Routing3247b97,
    RoutingWasSavedButCouldNotBeAppliedCheck1d63565,
    Rules3ec0bc7,
    RussiaEd6c98e,
    SaveArchiveD337443,
    SaveBackup8af1a7f,
    SaveExport0873fc1,
    SaveQrCodeB18e38b,
    SavedC2b7708,
    SavedChangesAreNotAppliedCd58464,
    SavedForNextConnection24dc1bb,
    SavedMode6858c31,
    SavedProfile59172eb,
    SavedRoutingIsAppliedB34e688,
    SubscriptionControlsRoutingD0cc60c,
    TextFilter,
    TheSettingWasSavedButCouldNotBeAppliedC499e90e,
    TrayAllowLan,
    TrayConnectionMode,
    TrayModeLocal,
    TrayModeSystemProxy,
    TrayModeTun,
    TrayRememberLastServer,
    TrayRestartConnection,
    TrayRestartThronium,
    TraySettingFailed,
    TraySettingReconnectFailed,
    TrayStartAtLogin,
    VpnAuthenticationRequiredC911203,
    VpnStateUnavailable1927156,
    VpnTunnelUnavailable718c206,
    WarpThroughTheSelectedServerB4d86c9,
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    WindowsQrConsent,
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    WindowsQrConsentCancel,
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    WindowsQrConsentCapture,
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    WindowsQtThroneRunning,
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    WindowsSessionEndReason,
    Working8ba5b78,
}
#[rustfmt::skip]
impl TextKey { pub fn as_str(self) -> &'static str { match self {
    Self::AllTrafficThroughProxy0c33426 => "all_traffic_through_proxy_0c33426",
    Self::ApplySavedChanges68db303 => "apply_saved_changes_68db303",
    Self::AutoSelect => "auto_select",
    Self::BackupFilter => "backup_filter",
    Self::BackupOpenFilter => "backup_open_filter",
    Self::BlockAdvertisements7303abe => "block_advertisements_7303abe",
    Self::ChangePolicyInRoutingSettings84336e9 => "change_policy_in_routing_settings_84336e9",
    Self::ChinaB2aa98d => "china_b2aa98d",
    Self::ChooseCoreExecutable087bad5 => "choose_core_executable_087bad5",
    Self::ChoosePolicyResource => "choose_policy_resource",
    Self::ConnectA27ba0c => "connect_a27ba0c",
    Self::ConnectToServer87401c4 => "connect_to_server_87401c4",
    Self::Connected8582d18 => "connected_8582d18",
    Self::ConnectingToVpnE25b29b => "connecting_to_vpn_e25b29b",
    Self::CoreUnavailable9f988f6 => "core_unavailable_9f988f6",
    Self::CouldNotChangeTheConnectionCheckTheProfilDc86529 => "could_not_change_the_connection_check_the_profil_dc86529",
    Self::CouldNotSaveRoutingTryAgainInRoutingSettAc73861 => "could_not_save_routing_try_again_in_routing_sett_ac73861",
    Self::CouldNotSaveThisSettingCheckTheAdblockWa9daf1aa => "could_not_save_this_setting_check_the_adblock_wa_9daf1aa",
    Self::DirectConnection17b0c96 => "direct_connection_17b0c96",
    Self::Disconnect2d5128c => "disconnect_2d5128c",
    Self::Disconnected47d3ebf => "disconnected_47d3ebf",
    Self::Favorites3fcf8bf => "favorites_3fcf8bf",
    Self::FullConfigurationControlsRoutingF940dbc => "full_configuration_controls_routing_f940dbc",
    Self::Groups6af1c99 => "groups_6af1c99",
    Self::Iran0aec67d => "iran_0aec67d",
    Self::LoadProfile6dd7d64 => "load_profile_6dd7d64",
    Self::NoServersDa4c36b => "no_servers_da4c36b",
    Self::NotificationConnectionLost => "notification_connection_lost",
    Self::NotificationConnectionLostBody => "notification_connection_lost_body",
    Self::NotificationReconnecting => "notification_reconnecting",
    Self::NotificationReconnectingBody => "notification_reconnecting_body",
    Self::NotificationRestored => "notification_restored",
    Self::NotificationRestoredBody => "notification_restored_body",
    Self::NotificationSubscriptionsChanged => "notification_subscriptions_changed",
    Self::NotificationSubscriptionsChangedBody => "notification_subscriptions_changed_body",
    Self::OpenBackup53325a0 => "open_backup_53325a0",
    Self::OpenThronium5ce46db => "open_thronium_5ce46db",
    Self::OtpCodes83b6c30 => "otp_codes_83b6c30",
    Self::Personal09c5ff5 => "personal_09c5ff5",
    Self::Quit9f9f8cf => "quit_9f9f8cf",
    Self::ReconnectingAef685e => "reconnecting_aef685e",
    Self::Routing3247b97 => "routing_3247b97",
    Self::RoutingWasSavedButCouldNotBeAppliedCheck1d63565 => "routing_was_saved_but_could_not_be_applied_check_1d63565",
    Self::Rules3ec0bc7 => "rules_3ec0bc7",
    Self::RussiaEd6c98e => "russia_ed6c98e",
    Self::SaveArchiveD337443 => "save_archive_d337443",
    Self::SaveBackup8af1a7f => "save_backup_8af1a7f",
    Self::SaveExport0873fc1 => "save_export_0873fc1",
    Self::SaveQrCodeB18e38b => "save_qr_code_b18e38b",
    Self::SavedC2b7708 => "saved_c2b7708",
    Self::SavedChangesAreNotAppliedCd58464 => "saved_changes_are_not_applied_cd58464",
    Self::SavedForNextConnection24dc1bb => "saved_for_next_connection_24dc1bb",
    Self::SavedMode6858c31 => "saved_mode_6858c31",
    Self::SavedProfile59172eb => "saved_profile_59172eb",
    Self::SavedRoutingIsAppliedB34e688 => "saved_routing_is_applied_b34e688",
    Self::SubscriptionControlsRoutingD0cc60c => "subscription_controls_routing_d0cc60c",
    Self::TextFilter => "text_filter",
    Self::TheSettingWasSavedButCouldNotBeAppliedC499e90e => "the_setting_was_saved_but_could_not_be_applied_c_499e90e",
    Self::TrayAllowLan => "tray_allow_lan",
    Self::TrayConnectionMode => "tray_connection_mode",
    Self::TrayModeLocal => "tray_mode_local",
    Self::TrayModeSystemProxy => "tray_mode_system_proxy",
    Self::TrayModeTun => "tray_mode_tun",
    Self::TrayRememberLastServer => "tray_remember_last_server",
    Self::TrayRestartConnection => "tray_restart_connection",
    Self::TrayRestartThronium => "tray_restart_thronium",
    Self::TraySettingFailed => "tray_setting_failed",
    Self::TraySettingReconnectFailed => "tray_setting_reconnect_failed",
    Self::TrayStartAtLogin => "tray_start_at_login",
    Self::VpnAuthenticationRequiredC911203 => "vpn_authentication_required_c911203",
    Self::VpnStateUnavailable1927156 => "vpn_state_unavailable_1927156",
    Self::VpnTunnelUnavailable718c206 => "vpn_tunnel_unavailable_718c206",
    Self::WarpThroughTheSelectedServerB4d86c9 => "warp_through_the_selected_server_b4d86c9",
    Self::WindowsQrConsent => "windows_qr_consent",
    Self::WindowsQrConsentCancel => "windows_qr_consent_cancel",
    Self::WindowsQrConsentCapture => "windows_qr_consent_capture",
    Self::WindowsQtThroneRunning => "windows_qt_throne_running",
    Self::WindowsSessionEndReason => "windows_session_end_reason",
    Self::Working8ba5b78 => "working_8ba5b78",
} } }
