"""Pinned openresolv in an owned Linux namespace; no host installation or DNS edits."""
import hashlib
import json
import os
from pathlib import Path
import subprocess

REVISION = 'fc72163141bbe2acd68e6d1ed473cfc30aa35eaf'
HASHES = {'resolvconf.in': '7e3c3f58dba7d1c16167d1b5576df6d033ed47c8867cbfe0629612a3e0c472cd',
          'libc.in': '9703e6999e0494a3749d976f72df08cf27606a7f5cf709ebc65d3a323a5d23f6'}


def install_private(upstream):
    assert os.getpid() == 1 and os.geteuid() == 0
    for kind in ('net', 'mnt'):
        assert os.readlink('/proc/self/ns/' + kind) != os.environ['THRONIUM_TEST_ORIGINAL_' + kind.upper() + 'NS']
    subprocess.run(['mount', '--make-rprivate', '/'], check=True)
    subprocess.run(['mount', '-t', 'tmpfs', '-o', 'mode=755', 'tmpfs', '/run'], check=True)
    root = Path('/run/thronium-openresolv')
    root.mkdir(mode=0o700)
    for name in ('bin', 'libexec', 'etc'):
        (root / name).mkdir(mode=0o755)
    replacements = {'@SYSCONFDIR@': str(root / 'etc'), '@SBINDIR@': str(root / 'bin'),
                    '@LIBEXECDIR@': str(root / 'libexec'), '@VARDIR@': '/run/resolvconf',
                    '@RCDIR@': '', '@RESTARTCMD@': '', '@STATUSARG@': ''}
    for source, target in [('resolvconf.in', 'bin/resolvconf'), ('libc.in', 'libexec/libc')]:
        body = (Path(upstream) / source).read_bytes()
        assert hashlib.sha256(body).hexdigest() == HASHES[source], source
        text = body.decode()
        for before, after in replacements.items():
            text = text.replace(before, after)
        p = root / target
        p.write_text(text)
        p.chmod(0o755)
    # Config and subscriber service hook are entirely private. The CLI and libc
    # algorithms themselves are genuine upstream Makefile template substitutions.
    (root / 'etc/resolvconf.conf').write_text('resolv_conf=/etc/resolv.conf\nlibc_restart=:\n')
    resolver = Path('/etc/resolv.conf').resolve()
    assert str(resolver).startswith('/run/'), 'fixture requires a resolver target under private /run'
    resolver.parent.mkdir(parents=True, exist_ok=True)
    resolver.write_text('# Generated by resolvconf\nnameserver 192.0.2.53\n')
    # Host root-owned files map to overflow UID in this user namespace. Give the
    # fixture its own root directory and fixed installed entry without weakening
    # production ownership validation or changing any host path.
    old_sbin = Path('/run/thronium-host-sbin')
    old_sbin.mkdir()
    subprocess.run(['mount', '--bind', '/usr/sbin', str(old_sbin)], check=True)
    sbin = Path('/run/thronium-sbin')
    sbin.mkdir()
    for source in old_sbin.iterdir():
        (sbin / source.name).symlink_to(source)
    installed = sbin / 'resolvconf'
    installed.unlink(missing_ok=True)
    installed.symlink_to(root / 'bin/resolvconf')
    subprocess.run(['mount', '--bind', str(sbin), '/usr/sbin'], check=True)
    chroot = Path('/run/thronium-root')
    chroot.mkdir(mode=0o755)
    subprocess.run(['mount', '--bind', str(chroot), str(chroot)], check=True)
    for name in ('usr', 'etc', 'dev', 'proc', 'sys', 'home', 'tmp', 'run', 'opt', 'var', 'bin', 'sbin', 'lib', 'lib64'):
        source = Path('/') / name
        if not source.exists():
            continue
        target = chroot / source.name
        if source.is_symlink():
            target.symlink_to(os.readlink(source))
        elif source.is_dir():
            target.mkdir()
            subprocess.run(['mount', '--rbind' if source.name in ('dev', 'sys', 'proc', 'home', 'var', 'usr') else '--bind', str(source), str(target)], check=True)
        elif source.is_file():
            target.touch()
            subprocess.run(['mount', '--rbind' if source.name in ('dev', 'sys', 'proc', 'home', 'var', 'usr') else '--bind', str(source), str(target)], check=True)
    os.chroot(chroot)
    os.chdir('/')
    subprocess.run(['ip', 'link', 'set', 'lo', 'up'], check=True)
    call(['-a', 'eth0.dhcp'], 'search old.test\nnameserver 192.0.2.53\n')


def call(args, body='', expected=0):
    result = subprocess.run(['/usr/sbin/resolvconf', *args], input=body, text=True,
                            capture_output=True, timeout=5,
                            env={'PATH': '/usr/sbin:/usr/bin:/sbin:/bin', 'LC_ALL': 'C'})
    assert result.returncode == expected, (args, result.returncode, result.stderr)
    return result.stdout
