"""Native TLS URI/field round trips and loopback ClientHello from saved profiles."""
import base64
import contextlib
import copy
import http.client
import json
import os
from pathlib import Path
import socket
import socketserver
import threading
import time
from urllib.parse import urlencode,urlsplit,parse_qs


def run(h):
    command,click,fill,select,wait_for,js,check=(h[k] for k in ('command','click','fill','select','wait_for','js','check'))
    initial=command('snapshot');geometry=h['request']('GET',h['base']+'/window/rect');original_presets=command('settings')['presets'];original_core=command('settings')['core']
    ready=json.loads(Path(os.environ['_THRONIUM_PROFILE_TLS_READY']).read_text());events=Path(ready['events'])
    group=command('saveGroup',{'name':'TLS native fixtures','subscription':None})['id'];target=command('saveGroup',{'name':'TLS round trips','subscription':None})['id']
    audit={'checks':[],'http':[],'clientHello':[]};ids=[];held=None
    class Echo(socketserver.BaseRequestHandler):
        def handle(self):
            with contextlib.suppress(OSError):
                while data:=self.request.recv(4096):self.request.sendall(data)
    class Server(socketserver.ThreadingTCPServer):allow_reuse_address=True;daemon_threads=True
    echo_server=Server(('127.0.0.1',0),Echo);threading.Thread(target=echo_server.serve_forever,daemon=True).start()
    def available():
        with socket.socket() as s:s.bind(('127.0.0.1',0));return s.getsockname()[1]
    def close():
        click('#main-modal > .modal-head > button')
        if js('return !!document.querySelector("[data-confirm-accept]")'):click('[data-confirm-accept]')
        wait_for('return !document.querySelector("dialog[open]")')
    def menu(id,item):
        click('.primary-nav button:first-child');selector='[data-profile-menu='+json.dumps(id)+']'
        wait_for('return !!document.querySelector('+json.dumps(selector)+')')
        # The real menu dismisses on scrolling. Drain the scroll generated by
        # bringing a newly added row into view before opening that menu.
        js('window.__tlsScrollAt=Date.now();window.__tlsScroll=()=>window.__tlsScrollAt=Date.now();document.addEventListener("scroll",window.__tlsScroll,true);document.querySelector(arguments[0]).scrollIntoView({block:"center",behavior:"instant"})',selector)
        wait_for('return Date.now()-window.__tlsScrollAt>150')
        js('document.removeEventListener("scroll",window.__tlsScroll,true);delete window.__tlsScroll;delete window.__tlsScrollAt')
        click(selector);click(item)
    def editor(id):
        menu(id,'#menu-edit-profile');wait_for('return !!document.querySelector("#profile-editor")');click('[data-profile-tab=tls]')
    def value(path):return js('return document.querySelector(arguments[0]).value','[data-field='+json.dumps(path)+']')
    def choose(path,text):select('[data-field='+json.dumps(path)+']',text)
    def edit(path,text):fill('[data-field='+json.dumps(path)+']',text)
    def draft():
        click('[data-profile-tab=json]');result=json.loads(js('return document.querySelector("#profile-json").value'));click('[data-profile-tab=tls]');return result
    def save():click('button[form=profile-editor]');wait_for('return !document.querySelector("dialog[open]")')
    def profile(id):return command('profile',{'id':id})
    def check_core(id):
        command('checkProfile',profile(id));audit['checks'].append({'id':id,'passed':True})
    def add(name,config,kind='sing-box-outbound'):
        id=command('saveProfile',{'name':name,'groupId':group,'kind':kind,'config':config})['id'];ids.append(id);return id
    def import_text(text,destination=group):
        before={p['id'] for p in command('snapshot')['profiles']}
        click('.add-connection');click('#add-choice-link');fill('#import-source',text);select('#import-group',destination);click('#import-review')
        wait_for('return document.querySelectorAll(".import-select").length===1');assert not js('return !!document.querySelector(".import-acknowledge")')
        click('#import-save');wait_for('return !document.querySelector("dialog[open]")')
        result=[p['id'] for p in command('snapshot')['profiles'] if p['id'] not in before];assert len(result)==1;return result[0]
    def export(id,format=None,expect_error=False):
        menu(id,'#export-one');wait_for('return !!document.querySelector("#configuration-share")');click('#configuration-share')
        if format:select('#export-format',format)
        click('#export-reveal')
        if expect_error:
            wait_for('return !!document.querySelector("dialog:not(#main-modal) [role=alert]")');text=js('return document.querySelector("dialog:not(#main-modal) [role=alert]").textContent')
        else:
            wait_for('return !!document.querySelector("#export-content")');text=js('return document.querySelector("#export-content").textContent')
        click('dialog:not(#main-modal) > .modal-head > button');wait_for('return document.querySelectorAll("dialog[open]").length===1');close();return text
    def effective(id):
        parts=command('connectionConfiguration',{'id':id,'active':False})['parts'];return parts[0]['config']
    def tls_out(id):
        cfg=effective(id);return next(o['tls'] for o in cfg['outbounds'] if o.get('tag')=='proxy')
    def set_presets(**values):
        old=command('settings')['presets'];command('saveSettings',{'section':'presets','previous':old,'values':{**old,**values}})
    def echo(label):
        packet=('tls-editor:'+label).encode();held.sendall(packet);got=b''
        while len(got)<len(packet):got+=held.recv(len(packet)-len(got))
        return got==packet
    def rows():return [json.loads(line) for line in events.read_text().splitlines()] if events.exists() else []
    try:
        command('preferences',{**initial['preferences'],'language':'en','theme':'dark','connectionMode':'local','vlessCore':'sing-box'})
        wait_for('return document.documentElement.lang==="en"');select('.group-strip select','all')
        set_presets(tls_tricks_default_on=False,tls_spoof_default_on=False)
        variants={}
        for state in [None,True,False]:
            params={'security':'tls','sni':'native-tls.test','tls_curve_preferences':'X25519,P256','tls_spoof':'spoof.native.test','tls_spoof_method':'wrong-sequence'}
            if state is not None:params.update(tls_tricks=str(state).lower(),tls_spoof_enabled=str(state).lower())
            uri='vless://00000000-0000-0000-0000-000000000001@127.0.0.1:9?'+urlencode(params)+'#TLS-'+str(state)
            id=import_text(uri);variants[state]=id;cfg=profile(id)['config'];tls=cfg['tls']
            expected=None if state is None else {'mixedcase_sni':state}
            absent=state is not None or ('tls_tricks' not in tls and 'spoof_enabled' not in tls)
            check(absent and tls.get('tls_tricks')==expected and tls.get('spoof_enabled') is state and tls['curve_preferences']==['X25519','P256'],'native URI import preserves distinct absent/true/false controls and TLS curve order: '+str(state))
            check_core(id);check(profile(id)['config']==cfg,'real Core Check accepts imported controls without rewriting saved JSON: '+str(state))
            editor(id);check(value('tls.tls_tricks.mixedcase_sni')==('' if state is None else str(state).lower()) and value('tls.spoof_enabled')==('' if state is None else str(state).lower()),'TLS fields display imported Default/Enabled/Disabled states: '+str(state));close()
            shared=export(id);query=parse_qs(urlsplit(shared).query,keep_blank_values=True)
            check(query.get('tls_tricks')==(None if state is None else [str(state).lower()]) and query.get('tls_spoof_enabled')==(None if state is None else [str(state).lower()]),'native URI export retains explicit false and does not invent absent switches: '+str(state))
            imported=import_text(shared,target);check(profile(imported)['config']==cfg,'native exported link reimports without losing TLS fields: '+str(state))
        id=variants[True];before=profile(id)['config'];editor(id)
        choose('tls.tls_tricks.mixedcase_sni','false');choose('tls.spoof_enabled','false');edit('tls.curve_preferences','P256\nX25519');edit('tls.spoof','edited-spoof.native.test');choose('tls.spoof_method','wrong-checksum')
        edited=draft();check(edited['tls']['tls_tricks']=={'mixedcase_sni':False} and edited['tls']['spoof_enabled'] is False and edited['tls']['curve_preferences']==['P256','X25519'],'structured TLS edits survive JSON-tab round trip with exact false values and curve ordering')
        click('.editor-modal .modal-footer .button.secondary');wait_for('return !!document.querySelector(".editor-modal [role=status]")')
        check(profile(id)['config']==before,'native Check validates the unsaved draft without modifying the saved profile');save();check(profile(id)['config']==edited,'Save persists all new TLS fields and existing credentials together')
        h['request']('POST',h['base']+'/refresh',{});wait_for('return !!document.querySelector(".add-connection")');editor(id)
        check(value('tls.spoof_method')=='wrong-checksum' and value('tls.curve_preferences')=='P256\nX25519' and value('tls.spoof_enabled')=='false','TLS controls survive a real WebView reload')
        choose('tls.tls_tricks.mixedcase_sni','');choose('tls.spoof_enabled','');cleared=draft()
        check('tls_tricks' not in cleared['tls'] and 'spoof_enabled' not in cleared['tls'] and cleared['tls']['spoof']=='edited-spoof.native.test','Default removes only the switch and an empty tricks object, preserving configured payload fields');close()
        check(profile(id)['config']==edited,'cancelling Default edits preserves the stored TLS configuration')
        old=copy.deepcopy(before);old['tls']['tls_tricks']=False;legacy=add('Legacy boolean tricks',old);check_core(legacy);editor(legacy)
        check(value('tls.tls_tricks.mixedcase_sni')=='false','older stored boolean tricks display through the same TLS control');choose('tls.tls_tricks.mixedcase_sni','true');check(draft()['tls']['tls_tricks']=={'mixedcase_sni':True},'editing a legacy boolean converts only that known control to its object form');close()
        portable=export(legacy);roundtrip=import_text(portable,target);check(profile(legacy)['config']==old and profile(roundtrip)['config']['tls']['tls_tricks']=={'mixedcase_sni':False},'legacy URI export is normalized semantically without rewriting the original stored boolean')
        unknown=copy.deepcopy(before);unknown['tls']['tls_tricks']['future']={'token':'synthetic-tls-hidden'};future=add('Unknown tricks sibling',unknown);editor(future);choose('tls.tls_tricks.mixedcase_sni','');preserved=draft();check(preserved['tls']['tls_tricks']=={'future':{'token':'synthetic-tls-hidden'}},'Default keeps unknown tricks siblings byte-for-value in the editor');save()
        message=export(future,expect_error=True);check('synthetic-tls-hidden' not in message and 'future' in message,'a lossy native URI export refuses unknown TLS fields without exposing their values')
        portable=export(future,'thronium-link');bundle=json.loads(base64.urlsafe_b64decode(portable.split('/profiles/',1)[1]+'==='));check(bundle['profiles'][0]['config']==preserved,'full Thronium export retains unknown TLS data exactly');imported=import_text(portable,target);check(profile(imported)['config']==preserved,'portable TLS fallback reimports with every unknown sibling intact')
        for malformed in [[],7,'invalid-tricks']:
            config=copy.deepcopy(before);config['tls']['tls_tricks']=malformed;bad=add('Malformed tricks '+type(malformed).__name__,config);editor(bad);choose('tls.tls_tricks.mixedcase_sni','true')
            check(js('return document.querySelector(\'[data-field="tls.tls_tricks.mixedcase_sni"]\').getAttribute("aria-invalid")==="true"') and draft()==config,'malformed imported tricks remain exact instead of losing a dropdown edit: '+type(malformed).__name__)
            click('button[form=profile-editor]');wait_for('return !!document.querySelector("#profile-editor [role=alert]")')
            check(profile(bad)['config']==config and js('return !!document.querySelector("#profile-editor")'),'Save refuses unresolved malformed tricks without changing the stored profile: '+type(malformed).__name__)
            click('[data-profile-tab=json]');corrected=copy.deepcopy(config);corrected['tls']['tls_tricks']={'mixedcase_sni':False};fill('#profile-json',json.dumps(corrected));save();check(profile(bad)['config']==corrected,'explicit JSON correction clears the invalid field and saves without hidden data loss: '+type(malformed).__name__)
        set_presets(tls_tricks_default_on=True,tls_spoof_default_on=True,tls_spoof='global-spoof.native.test',tls_spoof_method='wrong-sequence')
        compiled=tls_out(variants[False]);check(compiled['tls_tricks']['mixedcase_sni'] is False and 'spoof_enabled' not in compiled and 'spoof' not in compiled and 'spoof_method' not in compiled,'explicit Off overrides global spoof/tricks defaults on the runtime copy')
        inherited=copy.deepcopy(before);inherited['tls'].pop('tls_tricks',None);inherited['tls'].pop('spoof_enabled',None);inherited['tls'].pop('spoof',None);inherited['tls'].pop('spoof_method',None);inherit_id=add('TLS inherited defaults',inherited)
        compiled=tls_out(inherit_id);check(compiled['tls_tricks']['mixedcase_sni'] is True and compiled['spoof']=='global-spoof.native.test' and profile(inherit_id)['config']==inherited,'Default uses global controls while source JSON remains unchanged')
        sentinel=copy.deepcopy(inherited);sentinel['tls'].update(spoof='',spoof_method='');sentinel_id=add('Legacy explicit Off sentinel',sentinel);check_core(sentinel_id);compiled=tls_out(sentinel_id)
        check(not compiled.get('spoof') and not compiled.get('spoof_method') and 'spoof_enabled' not in compiled and profile(sentinel_id)['config']==sentinel,'older empty spoof strings remain Off under global On without rewriting their saved representation')
        editor(sentinel_id);check(value('tls.spoof_enabled')=='false','the legacy empty sentinel displays its effective Off state rather than Default')
        choose('tls.spoof_enabled','');reset=draft();check(all(k not in reset['tls'] for k in ['spoof_enabled','spoof','spoof_method']),'an explicit Off-to-Default selection removes only the legacy empty sentinel');save();check_core(sentinel_id)
        check(tls_out(sentinel_id)['spoof']=='global-spoof.native.test' and profile(sentinel_id)['config']==reset,'an explicit Default selection enables global inheritance while retaining the saved JSON exactly')
        empty_uri='vless://00000000-0000-0000-0000-000000000001@127.0.0.1:9?'+urlencode({'security':'tls','sni':'native-tls.test','tls_spoof':'','tls_spoof_method':''})+'#URI-empty-Default'
        empty_id=import_text(empty_uri);empty_tls=profile(empty_id)['config']['tls']
        check(all(k not in empty_tls for k in ['spoof_enabled','spoof','spoof_method']) and tls_out(empty_id)['spoof']=='global-spoof.native.test','empty URI parameters mean Default rather than creating an old stored Off sentinel')
        raw={'inbounds':[],'outbounds':[{'type':'http','tag':'proxy','server':'127.0.0.1','server_port':9,'tls':{'enabled':True,'server_name':'native-tls.test','tls_tricks':False,'spoof_enabled':False}}]};full=add('Opaque client TLS',raw,'sing-box-config')
        try:check_core(full);raise AssertionError('Opaque invalid core TLS fields must not be normalized')
        except RuntimeError:pass
        check(profile(full)['config']==raw and effective(full)['outbounds'][0]['tls']==raw['outbounds'][0]['tls'],'full client JSON bypasses client-only TLS normalization and remains exact after a Core rejection')
        stored_core=profile(id).get('vlessCore');stored_config=profile(id)['config'];editor(id);click('[data-profile-tab=main]');select('#editor-vless-core','xray');click('.editor-modal .modal-footer .button.secondary');wait_for('return !!document.querySelector("#profile-editor [role=alert]")')
        check(profile(id)['config']==stored_config and profile(id).get('vlessCore')==stored_core,'an incompatible Xray Check refuses these sing-box TLS fields without saving a core override or losing source options');close()
        set_presets(tls_tricks_default_on=False,tls_spoof_default_on=False)
        # Existing connection must survive Check/edit/export on another profile.
        port=available();command('preferences',{**command('snapshot')['preferences'],'inboundPort':port});direct=add('TLS editor held socket',{'type':'direct'});command('connect',{'id':direct})
        held=socket.create_connection(('127.0.0.1',port),timeout=3);destination='127.0.0.1:'+str(echo_server.server_address[1]);held.sendall(f'CONNECT {destination} HTTP/1.1\r\nHost: {destination}\r\n\r\n'.encode());header=b''
        while b'\r\n\r\n' not in header:header+=held.recv(4096)
        assert b' 200 ' in header;active=command('snapshot');editor(variants[False]);choose('tls.spoof_enabled','true');click('.editor-modal .modal-footer .button.secondary');wait_for('return !!document.querySelector(".editor-modal [role=status]")');close();export(variants[False])
        check(echo('retained') and command('snapshot')['running']==direct and command('snapshot')['since']==active['since'],'TLS Check, cancelled edits and export leave an existing real HTTP CONNECT socket and session intact');held.close();held=None;command('disconnect')
        for language in ['ru','en']:
            command('preferences',{**command('snapshot')['preferences'],'language':language});wait_for('return document.documentElement.lang==='+json.dumps(language));editor(id);h['request']('POST',h['base']+'/window/rect',{'width':390,'height':844})
            js('document.querySelector(\'[data-field="tls.spoof_enabled"]\').scrollIntoView({block:"center"})')
            check(js('const d=document.querySelector("dialog"),b=d.querySelector(".modal-body");return d.getBoundingClientRect().bottom<=innerHeight+1&&b.scrollWidth<=b.clientWidth+1') and value('tls.spoof_enabled')=='false',language+' TLS controls and footer fit the narrow native editor');h['screenshot']('profile-tls-'+language+'-390');close();h['request']('POST',h['base']+'/window/rect',{'width':1280,'height':860})
        proxy=add('Native TLS packet fixture',{'type':'http','server':'127.0.0.1','server_port':ready['proxyPort'],'tls':{'enabled':True,'server_name':ready['serverName'],'alpn':['http/1.1'],'spoof_enabled':False,'spoof':'must-not-appear.fixture.invalid','spoof_method':'wrong-sequence'}})
        for label,mixedcase,fragment in [('default','',False),('off','false',False),('on','true',False),('fragment','false',True)]:
            editor(proxy);choose('tls.tls_tricks.mixedcase_sni',mixedcase);choose('tls.spoof_enabled','false');choose('tls.fragment',str(fragment).lower());edit('tls.fragment_fallback_delay','10ms' if fragment else '');save()
            saved=profile(proxy)['config'];check_core(proxy);before_rows=len(rows());command('connect',{'id':proxy})
            path='/native-'+label;client=http.client.HTTPConnection('127.0.0.1',port,timeout=8)
            try:
                client.request('GET',f'http://127.0.0.1:{ready["originPort"]}'+path);response=client.getresponse();body=response.read();assert response.status==200 and body==('tls-fixture:'+path).encode()
            finally:client.close()
            command('disconnect');observed=rows()[before_rows:];hello=next(e for e in observed if e['event']=='client-hello');wire=hello['rawSni']
            audit['http'].append(path);audit['clientHello'].append({'label':label,'events':observed})
            check(wire==hello['sni'] and wire.lower()==ready['serverName'] and ((wire!=wire.lower()) if mixedcase=='true' else wire==ready['serverName']),label+' saved native TLS profile produces the expected raw ClientHello SNI and a real HTTP response')
            check(any(e['event']=='handshake' for e in observed) and any(e['event']=='connect' for e in observed) and any(e['event']=='http' and e['path']==path for e in observed) and profile(proxy)['config']==saved,label+' verifies the fixture certificate and preserves stored fields through TLS, CONNECT and HTTP')
        # Custom fragmentation must be observed at the owned TLS server, since
        # successful config validation alone cannot show record fragmentation.
        set_presets(fragment_default_on=True,fragment_implementation='custom',fragment_size='10-100',fragment_sleep='0')
        core_settings=command('settings')['core'];command('saveSettings',{'section':'core','previous':core_settings,'values':{**core_settings,'singbox_tcp_fast_open':'enabled'}})
        base_config={'type':'http','server':'127.0.0.1','server_port':ready['proxyPort'],'tls':{'enabled':True,'server_name':ready['serverName'],'alpn':['http/1.1'],'spoof_enabled':False,'tls_tricks':{'mixedcase_sni':False}}}
        custom=add('Native custom fragment fixture',base_config)
        for label,size in [('explicit','10-100'),('large','1500'),('maximum','65535'),('inherited',None)]:
            config=copy.deepcopy(base_config)
            if size is not None:config['tls_fragment']={'enabled':True,'size':size,'sleep':'0'}
            editor(custom)
            if size is not None:
                choose('tls_fragment.enabled','true');edit('tls_fragment.size',size);edit('tls_fragment.sleep','0')
            else:click('#custom-fragment-remove')
            save()
            check(profile(custom)['config']==config,label+' custom fragment fields save exact Core JSON without rewriting other fields')
            check_core(custom);out=next(o for o in effective(custom)['outbounds'] if o.get('tag')=='proxy')
            expected={'enabled':True,'size':size or '10-100','sleep':'0'}
            check(out.get('tls_fragment')==expected and out.get('tcp_fast_open') is not True,label+' custom fragment config suppresses inherited TFO in the Core request')
            before_rows=len(rows());command('connect',{'id':custom});path='/native-custom-'+label;client=http.client.HTTPConnection('127.0.0.1',port,timeout=8)
            try:
                client.request('GET',f'http://127.0.0.1:{ready["originPort"]}'+path);response=client.getresponse();body=response.read();assert response.status==200 and body==('tls-fixture:'+path).encode()
            finally:client.close()
            command('disconnect');observed=rows()[before_rows:];hello=next(e for e in observed if e['event']=='client-hello');sizes=hello['handshakeRecordSizes'];maximum=int((size or '10-100').split('-')[-1])
            check(bool(sizes) and all(0<n<=maximum for n in sizes) and (maximum>100 or len(sizes)>1),label+' custom fragmentation has the requested TLS record sizes on the actual wire')
            check(hello['rawSni']==ready['serverName'] and any(e['event']=='handshake' for e in observed) and any(e['event']=='connect' for e in observed) and any(e['event']=='http' and e['path']==path for e in observed) and profile(custom)['config']==config,label+' completes certificate-verified TLS, CONNECT and HTTP while retaining the source JSON')
            audit['http'].append(path);audit['clientHello'].append({'label':'custom-'+label,'events':observed})
        # Validate draft failures while an independent main connection stays up.
        active=add('Custom fragment check isolation',{'type':'direct'});command('connect',{'id':active})
        active_before=command('connectionConfiguration',{'id':active,'active':True})['parts']
        held=socket.create_connection(('127.0.0.1',port),timeout=5);held.sendall(f'CONNECT 127.0.0.1:{echo_server.server_address[1]} HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n'.encode());header=b''
        while not header.endswith(b'\r\n\r\n'):header+=held.recv(1)
        assert b' 200 ' in header
        for label,fragment,tfo in [('zero',{'enabled':True,'size':'0','sleep':'0'},False),('zero-min',{'enabled':True,'size':'0-10','sleep':'0'},False),('extra-bound',{'enabled':True,'size':'10-20-30','sleep':'0'},False),('overflow',{'enabled':True,'size':'65536','sleep':'0'},False),('sleep-format',{'enabled':True,'size':'10','sleep':'0-1-2'},False),('tfo-conflict',{'enabled':True,'size':'10','sleep':'0'},True)]:
            config=copy.deepcopy(base_config);config['tls_fragment']=fragment;config['tcp_fast_open']=tfo;draft_profile={**profile(custom),'config':config}
            # The boundary carries only a code; the Core reason stays in the log.
            try:command('checkProfile',draft_profile)
            except RuntimeError:pass
            else:raise AssertionError(label+' invalid fragment config accepted')
            check(echo('custom-check-'+label) and command('connectionConfiguration',{'id':active,'active':True})['parts']==active_before,label+' custom fragment draft is rejected without disturbing the held main connection')
        held.close();held=None;command('disconnect')
        for label,extra in [('explicit-tfo',{'tcp_fast_open':True}),('builtin',{'tls':{**base_config['tls'],'fragment':True}}),('disabled-custom',{'tls_fragment':{'enabled':False,'size':'retained disabled text','sleep':'retained disabled text'}})]:
            config={**copy.deepcopy(base_config),**extra};id=add('Fragment precedence '+label,config);check_core(id);out=next(o for o in effective(id)['outbounds'] if o.get('tag')=='proxy')
            check(out.get('tls_fragment',{}).get('enabled') is not True and profile(id)['config']==config,label+' preserves explicit imported semantics against the global custom preset')
        audit['customFragmentationPassed']=True
        # Dedicated field validation, imported unknown values and explicit reset.
        config={**copy.deepcopy(base_config),'tls_fragment':{'enabled':True,'size':'10-100','sleep':'0','method':'tlsHello','range':'1-2'}}
        form=add('Custom fragment field round trip',config);editor(form)
        check(value('tls_fragment.enabled')=='true' and value('tls_fragment.size')=='10-100' and value('tls_fragment.sleep')=='0' and draft()==config,'custom controls read imported JSON and retain unexposed method/range settings')
        for path,text in [('tls_fragment.size','0'),('tls_fragment.size','0-10'),('tls_fragment.size','1-2-3'),('tls_fragment.size','65536'),('tls_fragment.sleep','-1'),('tls_fragment.sleep','65536')]:
            edit(path,text)
            check(js('return document.querySelector(arguments[0]).getAttribute("aria-invalid")==="true"','[data-field='+json.dumps(path)+']') and draft()==config,path+' rejects '+text+' while retaining the last valid JSON')
            click('.editor-modal .modal-footer .button.secondary');wait_for('return !!document.querySelector("#profile-editor [role=alert]")')
            click('button[form=profile-editor]');wait_for('return !!document.querySelector("#profile-editor [role=alert]")')
            check(profile(form)['config']==config and js('return !!document.querySelector("#profile-editor")'),path+' invalid buffer blocks Check and Save without changing the stored profile')
            edit(path,config['tls_fragment'][path.split('.')[-1]])
        choose('tls_fragment.enabled','');expected=copy.deepcopy(config);del expected['tls_fragment']['enabled']
        check(draft()==expected,'Not set removes only the custom enabled switch and retains all sibling parameters')
        choose('tls_fragment.enabled','true');save();check(profile(form)['config']==config,'corrected custom fields save the original imported representation exactly')
        for malformed in [None,True,0,'invalid',[False]]:
            bad_config={**copy.deepcopy(base_config),'tls_fragment':malformed};bad=add('Malformed custom '+type(malformed).__name__,bad_config);editor(bad);edit('tls_fragment.size','10')
            check(js('return document.querySelector(arguments[0]).getAttribute("aria-invalid")==="true"','[data-field="tls_fragment.size"]') and draft()==bad_config,'malformed custom '+type(malformed).__name__+' is retained after a refused field edit')
            click('button[form=profile-editor]');wait_for('return !!document.querySelector("#profile-editor [role=alert]")');assert profile(bad)['config']==bad_config
            click('#custom-fragment-remove');save()
            check(profile(bad)['config']==base_config,'explicit custom removal clears the malformed block and its invalid field buffer: '+type(malformed).__name__)
        conflict={**copy.deepcopy(config),'tcp_fast_open':True};conflict_id=add('Custom TFO conflict',conflict);editor(conflict_id)
        check(js('return !!document.querySelector("#custom-fragment-tfo")'),'custom/TFO conflict explains which Advanced setting must change')
        click('.editor-modal .modal-footer .button.secondary');wait_for('return !!document.querySelector("#profile-editor [role=alert]")')
        check(profile(conflict_id)['config']==conflict,'native Check reports the custom/TFO conflict while the saved JSON stays exact');close()
        unknown={**copy.deepcopy(base_config),'tcp_fast_open':False,'tls':{**base_config['tls'],'fragment':False},'tls_fragment':{'enabled':False,'size':'10-100','sleep':'0','future':{'keep':[1,False]}}}
        unknown_id=add('Custom unknown sibling',unknown);editor(unknown_id);edit('tls_fragment.size','1500');save();expected=copy.deepcopy(unknown);expected['tls_fragment']['size']='1500'
        check(profile(unknown_id)['config']==expected,'one custom field edit retains imported unknown JSON and explicit builtin/TFO switches')
        editor(unknown_id);click('#custom-fragment-remove');save();del expected['tls_fragment']
        check(profile(unknown_id)['config']==expected,'explicit Remove custom settings deletes the entire block while retaining builtin/TFO and the rest of the profile')
        for language in ['ru','en']:
            command('preferences',{**command('snapshot')['preferences'],'language':language});wait_for('return document.documentElement.lang==='+json.dumps(language));editor(form)
            h['request']('POST',h['base']+'/window/rect',{'width':390,'height':844})
            wait_for('return innerWidth===390&&innerHeight===844')
            js('document.querySelector(arguments[0]).scrollIntoView({block:"start",behavior:"instant"})','[data-field="tls_fragment.enabled"]')
            samples=[]
            for _ in range(3):
                samples.append(js('const b=document.querySelector(".modal-body"),r=document.querySelector(arguments[0]).getBoundingClientRect();return {w:innerWidth,h:innerHeight,scroll:b.scrollTop,x:r.x,y:r.y,width:r.width,height:r.height}','[data-field="tls_fragment.size"]'))
                time.sleep(.15)
            assert samples[0]==samples[1]==samples[2]
            audit.setdefault('customFragmentGeometry',{})[language]=samples
            check(js('const d=document.querySelector("dialog"),b=d.querySelector(".modal-body");return d.getBoundingClientRect().bottom<=innerHeight+1&&b.scrollWidth<=b.clientWidth+1') and value('tls_fragment.size')=='10-100' and value('tls_fragment.sleep')=='0',language+' custom fields, range hints and footer fit the narrow native editor')
            h['screenshot']('custom-fragment-'+language+'-390');close();h['request']('POST',h['base']+'/window/rect',{'width':1280,'height':860})
        audit['customFragmentFieldsPassed']=True
    finally:
        if held:held.close()
        with contextlib.suppress(Exception):
            if js('return !!document.querySelector("#main-modal")'):close()
            command('disconnect')
            current=command('settings')['presets'];command('saveSettings',{'section':'presets','previous':current,'values':original_presets})
            current_core=command('settings')['core'];command('saveSettings',{'section':'core','previous':current_core,'values':original_core})
            command('deleteGroup',{'id':group,'deleteProfiles':True});command('deleteGroup',{'id':target,'deleteProfiles':True});command('preferences',initial['preferences'])
            h['request']('POST',h['base']+'/window/rect',geometry)
        (h['artifacts']/'profile-tls-audit.json').write_text(json.dumps(audit,indent=2)+'\n');echo_server.shutdown();echo_server.server_close()
