"""Existing default DNS/resource assertions with an isolated minimal fixture.

The original block is retained in native_smoke.py; its assertions are copied
verbatim here to allow routing regressions without unrelated library scenarios.
"""
import contextlib
import copy
import json
import os
from pathlib import Path
import socket
import uuid


def run(h):
    command,click,fill,select,wait_for,js,check,screenshot=(h[k] for k in ('command','click','fill','select','wait_for','js','check','screenshot'))
    initial=command('snapshot');original=command('routing');geometry=h['request']('GET',h['base']+'/window/rect')
    directory=Path(os.environ['XDG_DATA_HOME']);assert 'thronium-native-test-' in str(directory)
    def state():return json.loads((directory/'io.thronium.desktop/library.json').read_text())
    command('preferences',initial['preferences']);baseline=state();saved=None
    try:
        command('disconnect');command('preferences',{**initial['preferences'],'language':'en','theme':'dark'})
        wait_for('return document.documentElement.lang==="en"')
        h['request']('POST',h['base']+'/window/rect',{'width':1280,'height':860})
        with socket.socket() as available:available.bind(('127.0.0.1',0));proxy_port=available.getsockname()[1]
        command('connectionSettings',{'mode':'local','port':proxy_port})
        saved=command('saveProfile',{'name':'Existing DNS resource fixture','groupId':'personal','kind':'sing-box-outbound','config':{'type':'direct'}})
        preset={'id':str(uuid.uuid4()),'name':'Existing resource assertions','mode':'rules','rules':[],'route':{'final':'direct','auto_detect_interface':True,'default_domain_resolver':'dns-direct'},'dns':{'servers':[{'type':'local','tag':'dns-direct'}],'final':'dns-direct'}}
        command('saveRouting',{**original,'active':preset['id'],'profiles':[preset]})
        click('.primary-nav button:nth-child(2)');wait_for('return !!document.querySelector("#route-add-rule")')
        click('[data-route-tab="dns"]')
        click('#dns-add-server')
        select('#resource-type', 'hosts')
        fill('#resource-tag', 'native-hosts')
        fill('#resource-predefined', 'resource.test 127.0.0.1')
        click('#resource-check')
        wait_for('return !!document.querySelector(".resource-modal .resource-notice")')
        check(True, 'structured hosts entries validate through the real core')
        screenshot('dns-hosts-editor-en')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        dns_resource = command('routing')['profiles'][0]['dns']
        check(dns_resource['servers'][1]['predefined'] == {'resource.test': ['127.0.0.1']}, 'hosts form saves real addresses')
        check(dns_resource['rules'][0]['preferred_by'] == ['native-hosts'], 'hosts creation installs a matching DNS rule')
        click('[data-resource-edit="server:1"]')
        fill('#resource-tag', 'renamed-hosts')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        check(command('routing')['profiles'][0]['dns']['rules'][0]['server'] == 'renamed-hosts', 'renaming a DNS server repairs its DNS rules')
        click('[data-resource-delete="server:1"]')
        click('#resource-delete-confirm')
        wait_for('return !!document.querySelector("dialog [role=alert]")')
        check(len(command('routing')['profiles'][0]['dns']['servers']) == 2, 'referenced DNS server cannot be deleted')
        click('.modal-head .icon-button')
        click('#dns-options')
        click('[data-resource-tab="cache"]')
        fill('#resource-cache_capacity', '768')
        select('#resource-optimistic-enabled', 'true')
        fill('#resource-optimistic-timeout', '20s')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        check(command('routing')['profiles'][0]['dns']['cache_capacity'] == 768, 'structured DNS cache options persist')
        check(command('routing')['profiles'][0]['dns']['optimistic'] == {'enabled': True, 'timeout': '20s'}, 'optimistic cache serializes its object options')
        click('#dns-add-server')
        select('#resource-type', 'https')
        fill('#resource-tag', 'draft-https')
        fill('#resource-server', '127.0.0.1')
        click('[data-resource-tab="tls"]')
        fill('#resource-headers', '{unfinished')
        click('[data-resource-tab="main"]')
        select('#resource-type', 'udp')
        fill('#resource-tag', 'shared-name')
        select('#resource-type', 'https')
        check(js('return document.querySelector("#resource-tag").value') == 'shared-name', 'changing DNS type keeps the latest shared name')
        click('[data-resource-tab="tls"]')
        check(js('return document.querySelector("#resource-headers").value') == '{unfinished', 'unfinished HTTP headers survive DNS type switches')
        click('#resource-save')
        check(bool(js('return document.querySelector("dialog [role=alert]")')), 'invalid DNS fields block saving')
        click('.modal-head .icon-button')
        check(bool(js('return document.querySelector("#resource-discard")')), 'closing a modified DNS editor requires discarding its draft')
        click('#resource-discard')
        click('#dns-add-server')
        select('#resource-type', 'fakeip')
        fill('#resource-tag', 'native-fake')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        dns_resource = command('routing')['profiles'][0]['dns']
        check(dns_resource['servers'][-1]['inet4_range'] == '198.18.0.0/15' and dns_resource['rules'][-1]['server'] == 'native-fake', 'FakeIP form saves ranges and a final A / AAAA rule')
        click('[data-resource-delete="rule:1"]')
        click('#resource-delete-confirm')
        wait_for('return !document.querySelector("dialog")')
        click('[data-resource-delete="server:2"]')
        click('#resource-delete-confirm')
        wait_for('return !document.querySelector("dialog")')
        check(len(command('routing')['profiles'][0]['dns']['servers']) == 2, 'unused DNS server can be removed after its rule')
        click('#dns-add-rule')
        fill('#resource-domain_suffix', 'blocked.test')
        click('[data-resource-tab="action"]')
        select('#resource-action', 'predefined')
        fill('#resource-answer', 'blocked.test. 60 IN A 127.0.0.2')
        select('#resource-action', 'reject')
        select('#resource-action', 'predefined')
        check(js('return document.querySelector("#resource-answer").value') == 'blocked.test. 60 IN A 127.0.0.2', 'DNS action switches restore separate parameter drafts')
        select('#resource-action', 'reject')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        check(command('routing')['profiles'][0]['dns']['rules'][-1] == {'domain_suffix': ['blocked.test'], 'action': 'reject'}, 'DNS rule save omits parameters from a different action')
        click('[data-dns-rule-up="1"]')
        wait_for('return !document.querySelector("#dns-add-rule").disabled')
        check(command('routing')['profiles'][0]['dns']['rules'][0]['action'] == 'reject', 'DNS rule order changes in native storage')
        click('#dns-resolve-domains')
        wait_for('return !document.querySelector("#dns-add-rule").disabled')
        check(command('routing')['profiles'][0]['rules'][0]['config'] == {'action': 'resolve'}, 'DNS helper adds an explicit resolve rule before routing')
        command('connect', {'id': saved['id']})
        with socket.socket() as origin:
            origin.settimeout(5)
            origin.bind(('127.0.0.1', 0))
            origin.listen()
            address = 'resource.test:' + str(origin.getsockname()[1])
            with socket.create_connection(('127.0.0.1', proxy_port), timeout=5) as client:
                client.sendall(f'CONNECT {address} HTTP/1.1\r\nHost: {address}\r\n\r\n'.encode())
                upstream, _ = origin.accept()
                with upstream:
                    check(b'200' in client.recv(1024), 'hosts entered in the DNS form resolve a real proxy connection')
                    client.sendall(b'dns-form-test')
                    check(upstream.recv(1024) == b'dns-form-test', 'form-generated DNS and routing forward real bytes')
        command('disconnect')
        click('[data-route-tab="rules"]')
        resolve_id = command('routing')['profiles'][0]['rules'][0]['id']
        click(f'[data-delete-rule="{resolve_id}"]')
        click('#route-delete-confirm')
        wait_for('return !document.querySelector("dialog")')
        click('[data-route-tab="sets"]')
        click('#ruleset-add')
        select('#resource-type', 'inline')
        fill('#resource-tag', 'native-set')
        fill('#resource-rules', '[{"domain_suffix":["example.test"]}]')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        check(command('routing')['profiles'][0]['route']['rule_set'][0]['rules'] == [{'domain_suffix': ['example.test']}], 'structured inline rule set passes core validation and saves')
        click('[data-route-tab="dns"]')
        click('#dns-add-rule')
        fill('#resource-rule_set', 'native-set')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        click('[data-route-tab="sets"]')
        click('[data-resource-edit="set:0"]')
        fill('#resource-tag', 'renamed-set')
        click('#resource-save')
        wait_for('return !document.querySelector("dialog")')
        check(command('routing')['profiles'][0]['dns']['rules'][-1]['rule_set'] == ['renamed-set'], 'renaming a rule set repairs DNS references')
        click('[data-resource-delete="set:0"]')
        click('#resource-delete-confirm')
        wait_for('return !!document.querySelector("dialog [role=alert]")')
        check(len(command('routing')['profiles'][0]['route']['rule_set']) == 1, 'rule-set deletion protects DNS references')
        click('.modal-head .icon-button')
        screenshot('rule-sets-en')
        click('[data-route-tab="dns"]')
        screenshot('dns-servers-en')
        click('[data-resource-view="json"]')
        fill('#route-json', '{unfinished')
        click('[data-route-tab="rules"]')
        click('[data-route-tab="dns"]')
        click('[data-resource-view="json"]')
        check(js('return document.querySelector("#route-json").value') == '{unfinished', 'unfinished DNS JSON survives page-tab switches')
        click('[data-resource-view="fields"]')
        check(bool(js('return document.querySelector("#resource-json-discard")')), 'switching from edited DNS JSON to forms protects unsaved input')
        click('#resource-json-discard')
        click('[data-resource-view="json"]')
        dns = {'servers': [{'type': 'local', 'tag': 'dns-direct'}, {'type': 'hosts', 'tag': 'test-hosts', 'predefined': {'routing.test': '127.0.0.1'}}], 'final': 'dns-direct', 'cache_capacity': 512}
        fill('#route-json', json.dumps(dns))
        click('#route-json-save')
        wait_for('return !document.querySelector("#route-json-save").disabled')
        check(command('routing')['profiles'][0]['dns'] == dns, 'DNS and hosts settings persist after real core validation')
        click('[data-route-tab="sets"]')
        click('[data-resource-view="json"]')
        rule_sets = [{'type': 'inline', 'tag': 'native-set', 'rules': [{'domain_suffix': ['blocked.test']}]}]
        fill('#route-json', json.dumps(rule_sets))
        click('#route-json-save')
        wait_for('return !document.querySelector("#route-json-save").disabled')
        check(command('routing')['profiles'][0]['route']['rule_set'] == rule_sets, 'rule-set JSON is validated and persisted')
    finally:
        with contextlib.suppress(Exception):
            if js('return !!document.querySelector("dialog[open]")'):
                click('#main-modal > .modal-head > button')
                if js('return !!document.querySelector("[data-confirm-accept]")'):click('[data-confirm-accept]')
            command('disconnect');current=command('routing');command('saveRouting',{**current,'active':original['active'],'profiles':original['profiles']})
            if saved:command('deleteProfiles',{'ids':[saved['id']]})
            command('preferences',initial['preferences']);h['request']('POST',h['base']+'/window/rect',geometry)
    cleaned=state();expected=copy.deepcopy(baseline);expected['routing']['revision']=cleaned['routing']['revision']
    check(cleaned==expected,'resource regression cleanup preserves all original library values except the monotonic routing revision')
