//! Native wire contracts, generated frontend types and safe boundary errors.
mod catalog;
pub(crate) mod error_codes;
mod models;
pub mod schema;

use schema::Schema;
use serde::Serialize;
use serde_json::Value;
use std::{collections::BTreeMap, sync::OnceLock};

#[derive(Serialize)]
pub struct Command {
    pub request: Schema,
    pub response: Schema,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Registry {
    pub definitions: BTreeMap<String, Schema>,
    pub commands: BTreeMap<String, Command>,
    pub error_codes: &'static [&'static str],
}

pub fn registry() -> &'static Registry {
    static REGISTRY: OnceLock<Registry> = OnceLock::new();
    REGISTRY.get_or_init(|| Registry {
        definitions: models::definitions(),
        commands: catalog::commands(),
        error_codes: error_codes::codes(),
    })
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BoundaryError {
    pub code: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safe_params: Option<BTreeMap<String, String>>,
}

/// The registered code equal to `error`. Only such codes may be published in
/// status shared with the window or logs; anything else can carry user data.
pub(crate) fn registered(error: &str) -> Option<&'static str> {
    error_codes::codes()
        .iter()
        .copied()
        .find(|code| *code == error)
}

impl BoundaryError {
    pub fn code(code: &'static str) -> Self {
        Self {
            code,
            field: None,
            safe_params: None,
        }
    }
    pub fn legacy(error: &str) -> Self {
        // Internal errors may include URLs, core dumps or temporary credentials.
        // Only an explicitly registered leading code crosses the generic boundary.
        let candidate = error.split(':').next().unwrap_or("").trim();
        let code = error_codes::codes()
            .iter()
            .copied()
            .find(|code| *code == candidate)
            .unwrap_or("operation_failed");
        let mut result = Self::code(code);
        // These suffixes contain declared setting IDs, never user values.
        if matches!(
            code,
            "settings_invalid" | "settings_shortcut_unavailable" | "settings_conflict"
        ) {
            let ids: Vec<_> = error
                .split_once(':')
                .map(|(_, suffix)| suffix)
                .unwrap_or("")
                .split(',')
                .filter(|id| {
                    crate::settings::fields()
                        .iter()
                        .any(|field| field.id == *id)
                })
                .collect();
            if code == "settings_conflict" && !ids.is_empty() {
                result.safe_params = Some(BTreeMap::from([("fields".into(), ids.join(","))]));
            } else if let Some(id) = ids.first() {
                result.field = Some(format!("$.{id}"));
            }
        }
        result
    }
}

impl std::fmt::Display for BoundaryError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.code)
    }
}
impl std::error::Error for BoundaryError {}

impl Registry {
    pub fn request(&self, name: &str, payload: &Value) -> Result<&Command, BoundaryError> {
        let command = self
            .commands
            .get(name)
            .ok_or_else(|| BoundaryError::code("unknown_command"))?;
        command
            .request
            .validate(payload, &self.definitions)
            .map_err(|field| BoundaryError {
                field: Some(field),
                ..BoundaryError::code("invalid_command_payload")
            })?;
        Ok(command)
    }

    pub fn typescript(&self) -> String {
        let mut out = String::from("// Generated by thronium-engine export-contracts. Edit engine/src/ipc, then regenerate.\n");
        for (name, schema) in &self.definitions {
            out.push_str(&format!("export type {name} = {};\n", schema.typescript()));
        }
        out.push_str("export interface Models {\n");
        for name in self.definitions.keys() {
            out.push_str(&format!("  {name}: {name};\n"));
        }
        out.push_str("}\n");
        out.push_str("export interface Commands {\n");
        for (name, command) in &self.commands {
            out.push_str(&format!(
                "  {}: {{ request: {}; response: {} }};\n",
                serde_json::json!(name),
                command.request.typescript(),
                command.response.typescript()
            ));
        }
        out.push_str("}\nexport type CommandName = keyof Commands;\nexport type Request<K extends CommandName> = Commands[K]['request'];\nexport type Response<K extends CommandName> = Commands[K]['response'];\n");
        out.push_str(&format!(
            "export type ErrorCode = {};\n",
            self.error_codes
                .iter()
                .map(|code| serde_json::json!(code).to_string())
                .collect::<Vec<_>>()
                .join(" | ")
        ));
        out
    }
}

#[cfg(test)]
mod tests;
