//go:build linux

package tundns

import (
	"context"
	"fmt"
	"net/netip"
	"slices"
	"strings"
)

// OpenResolv manages one token-named record. Unlike resolved per-link policy,
// this record survives link deletion, so recovery deliberately does not consult
// a possibly removed or recycled kernel index before removing the owned record.
// The installed openresolv libc subscriber must manage /etc/resolv.conf directly;
// configurations that retain a local stub or prepend other servers fail readback.
type OpenResolv struct {
	command      resolvCommand
	readResolver func() ([]byte, error)
}
type resolvCommand func(context.Context, string, ...string) (string, int, error)

func resolvKey(s Spec) string { return "thronium-tun.thronium-" + s.Token }
func resolvBody(s Spec) string {
	body := fmt.Sprintf("# Thronium DNS %d %s\n", s.Index, s.Token)
	for _, a := range s.Servers {
		body += "nameserver " + a.String() + "\n"
	}
	return body
}
func resolverAddresses(body string) ([]netip.Addr, error) {
	if len(body) > 65536 || strings.ContainsRune(body, 0) {
		return nil, ErrInvalid
	}
	var addresses []netip.Addr
	for _, line := range strings.Split(body, "\n") {
		line = strings.SplitN(strings.SplitN(line, "#", 2)[0], ";", 2)[0]
		fields := strings.Fields(line)
		if len(fields) == 0 || fields[0] != "nameserver" {
			continue
		}
		if len(fields) != 2 {
			return nil, ErrInvalid
		}
		a, err := netip.ParseAddr(fields[1])
		if err != nil || a.Is4In6() {
			return nil, ErrInvalid
		}
		addresses = append(addresses, a)
	}
	return addresses, nil
}
func (c *OpenResolv) actual() ([]netip.Addr, error) {
	body, err := c.readResolver()
	if err != nil {
		return nil, ErrUnavailable
	}
	return resolverAddresses(string(body))
}

// record distinguishes missing state from command failure; openresolv -l uses
// exit 2 for an absent explicit key. Foreign data at the exact key is never erased.
func (c *OpenResolv) record(ctx context.Context, s Spec) (bool, error) {
	out, code, err := c.command(ctx, "", "-l", resolvKey(s))
	if err != nil {
		return false, ErrUnavailable
	}
	if code == 2 && out == "" {
		return false, nil
	}
	if code != 0 {
		return false, ErrUnavailable
	}
	if out != "# resolv.conf from "+resolvKey(s)+"\n"+resolvBody(s)+"\n" {
		return false, ErrOwnership
	}
	return true, nil
}
func (c *OpenResolv) exclusive(ctx context.Context, s Spec, required bool) bool {
	out, code, err := c.command(ctx, "", "-x")
	if err != nil || code != 0 {
		return false
	}
	keys := strings.Fields(out)
	return len(keys) == 1 && keys[0] == resolvKey(s) || !required && len(keys) == 0
}
func (c *OpenResolv) Matches(parent context.Context, owned Verify, s Spec) bool {
	ctx, cancel := context.WithTimeout(parent, Timeout)
	defer cancel()
	if s.Validate() != nil || verify(ctx, owned, s) != nil {
		return false
	}
	exists, err := c.record(ctx, s)
	if err != nil || !exists || !c.exclusive(ctx, s, true) {
		return false
	}
	actual, err := c.actual()
	return err == nil && slices.Equal(actual, s.Servers) && verify(ctx, owned, s) == nil
}
func (c *OpenResolv) Apply(parent context.Context, owned Verify, s Spec) error {
	if err := s.Validate(); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(parent, Timeout)
	defer cancel()
	if err := verify(ctx, owned, s); err != nil {
		return err
	}
	if _, err := c.record(ctx, s); err != nil {
		return err
	}
	// An administrator or another VPN already owns exclusive DNS: don't compete.
	if !c.exclusive(ctx, s, false) {
		return ErrOwnership
	}
	body, err := c.readResolver()
	if err != nil || !strings.HasPrefix(string(body), "# Generated by resolvconf\n") {
		return ErrUnavailable
	}
	if err := verify(ctx, owned, s); err != nil {
		return err
	}
	_, code, err := c.command(ctx, resolvBody(s), "-m", "0", "-x", "-a", resolvKey(s))
	if err == nil && code == 0 && c.Matches(ctx, owned, s) {
		return nil
	}
	if c.Revert(context.Background(), s) != nil {
		return ErrCleanup
	}
	return ErrApply
}
func (c *OpenResolv) Revert(parent context.Context, s Spec) error {
	if err := s.Validate(); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(parent, Timeout)
	defer cancel()
	if _, err := c.record(ctx, s); err != nil {
		return err
	}
	// -f -d also retries a failed subscriber update recorded by openresolv itself.
	// Never use -u: that can overwrite a resolver file owned by another manager.
	_, code, err := c.command(ctx, "", "-f", "-d", resolvKey(s))
	if err != nil || code != 0 {
		return ErrCleanup
	}
	exists, err := c.record(ctx, s)
	if err != nil {
		return err
	}
	if exists {
		return ErrCleanup
	}
	actual, err := c.actual()
	if err != nil {
		return ErrCleanup
	}
	for _, a := range s.Servers {
		if slices.Contains(actual, a) {
			return ErrCleanup
		}
	}
	return nil
}
