//go:build linux

package tundns

import (
	"context"
	"errors"
	"fmt"
	"net/netip"
	"slices"
	"strings"
	"testing"
)

type resolvFake struct {
	records                          map[string]string
	exclusive                        []string
	resolver                         string
	network                          string
	writes                           []string
	addFail, deleteFail, stale, stub bool
}

func newResolvFake() (*resolvFake, *OpenResolv) {
	f := &resolvFake{records: map[string]string{}, network: "192.0.2.53"}
	f.render()
	return f, &OpenResolv{command: f.run, readResolver: func() ([]byte, error) { return []byte(f.resolver), nil }}
}
func (f *resolvFake) render() {
	f.resolver = "# Generated by resolvconf\n"
	if f.stub {
		f.resolver += "nameserver 127.0.0.1\n"
		return
	}
	if len(f.exclusive) > 0 {
		for _, line := range strings.Split(f.records[f.exclusive[0]], "\n") {
			if strings.HasPrefix(line, "nameserver ") {
				f.resolver += line + "\n"
			}
		}
	} else {
		f.resolver += "nameserver " + f.network + "\n"
	}
}
func (f *resolvFake) run(ctx context.Context, body string, args ...string) (string, int, error) {
	if ctx.Err() != nil {
		return "", -1, ctx.Err()
	}
	key := args[len(args)-1]
	switch args[0] {
	case "-l":
		if v, ok := f.records[key]; ok {
			return "# resolv.conf from " + key + "\n" + v + "\n", 0, nil
		}
		return "", 2, nil
	case "-x":
		return strings.Join(f.exclusive, "\n"), 0, nil
	case "-m":
		f.writes = append(f.writes, "add")
		f.records[key] = body
		f.exclusive = []string{key}
		f.render()
		if f.addFail {
			return "", 1, nil
		}
		return "", 0, nil
	case "-f":
		f.writes = append(f.writes, "delete")
		if f.deleteFail {
			return "", 1, nil
		}
		delete(f.records, key)
		f.exclusive = slices.DeleteFunc(f.exclusive, func(s string) bool { return s == key })
		if !f.stale {
			f.render()
		}
		return "", 0, nil
	}
	return "", -1, fmt.Errorf("unexpected command")
}
func resolvSpec() Spec {
	return Spec{11, strings.Repeat("a", 32), []netip.Addr{netip.MustParseAddr("172.19.0.2"), netip.MustParseAddr("fdfe:dcba:9876::2")}}
}
func TestOpenResolvRestoresLatestNetworkAndCleansWithoutKernelLink(t *testing.T) {
	f, c := newResolvFake()
	s := resolvSpec()
	owned := func(Spec) error { return nil }
	if err := c.Apply(context.Background(), owned, s); err != nil {
		t.Fatal(err)
	}
	if !c.Matches(context.Background(), owned, s) {
		t.Fatal("not applied")
	}
	f.network = "198.51.100.53"
	f.render()
	if !c.Matches(context.Background(), owned, s) {
		t.Fatal("DHCP overrode exclusive DNS")
	}
	if err := c.Revert(context.Background(), s); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(f.resolver, "198.51.100.53") || strings.Contains(f.resolver, "172.19.0.2") || len(f.records) != 0 {
		t.Fatal("stale restoration")
	}
	if err := c.Revert(context.Background(), s); err != nil {
		t.Fatal("idempotent recovery", err)
	}
}
func TestOpenResolvForeignRecordAndExclusivePolicyArePreserved(t *testing.T) {
	for _, kind := range []string{"same-key", "exclusive", "link"} {
		t.Run(kind, func(t *testing.T) {
			f, c := newResolvFake()
			s := resolvSpec()
			owned := func(Spec) error { return nil }
			switch kind {
			case "same-key":
				f.records[resolvKey(s)] = "nameserver 192.0.2.99\n"
			case "exclusive":
				f.records["other.vpn"] = "nameserver 192.0.2.99\n"
				f.exclusive = []string{"other.vpn"}
			case "link":
				owned = func(Spec) error { return ErrOwnership }
			}
			if err := c.Apply(context.Background(), owned, s); !errors.Is(err, ErrOwnership) {
				t.Fatal(err)
			}
			if len(f.writes) != 0 {
				t.Fatal("foreign mutation")
			}
			if kind == "same-key" {
				if err := c.Revert(context.Background(), s); !errors.Is(err, ErrOwnership) {
					t.Fatal(err)
				}
				if len(f.writes) != 0 {
					t.Fatal("foreign cleanup")
				}
			}
		})
	}
}
func TestOpenResolvPartialFailureUnwindsOnlyOwnRecord(t *testing.T) {
	for _, kind := range []string{"add-error", "stub", "canceled"} {
		t.Run(kind, func(t *testing.T) {
			f, c := newResolvFake()
			s := resolvSpec()
			f.records["eth0.dhcp"] = "nameserver 192.0.2.53\n"
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			switch kind {
			case "add-error":
				f.addFail = true
			case "stub":
				f.stub = true
			case "canceled":
				cancel()
			}
			if err := c.Apply(ctx, func(Spec) error { return nil }, s); err == nil {
				t.Fatal("accepted failed apply")
			}
			if _, ok := f.records[resolvKey(s)]; ok {
				t.Fatal("record leaked")
			}
			if f.records["eth0.dhcp"] != "nameserver 192.0.2.53\n" {
				t.Fatal("network state changed")
			}
		})
	}
}
func TestOpenResolvCleanupRequiresRemovedRecordAndNoDeadResolver(t *testing.T) {
	for _, kind := range []string{"delete-error", "stale-file", "changed-record", "missing-stale-file"} {
		t.Run(kind, func(t *testing.T) {
			f, c := newResolvFake()
			s := resolvSpec()
			if err := c.Apply(context.Background(), func(Spec) error { return nil }, s); err != nil {
				t.Fatal(err)
			}
			switch kind {
			case "delete-error":
				f.deleteFail = true
			case "stale-file":
				f.stale = true
			case "changed-record":
				f.records[resolvKey(s)] += "# foreign\n"
			case "missing-stale-file":
				delete(f.records, resolvKey(s))
				f.stale = true
			}
			if err := c.Revert(context.Background(), s); err == nil {
				t.Fatal("unproven cleanup accepted")
			}
		})
	}
}
func TestOpenResolvWatchdogDetectsForeignChanges(t *testing.T) {
	for _, kind := range []string{"record", "exclusive", "file", "index"} {
		t.Run(kind, func(t *testing.T) {
			f, c := newResolvFake()
			s := resolvSpec()
			owned := func(Spec) error { return nil }
			if err := c.Apply(context.Background(), owned, s); err != nil {
				t.Fatal(err)
			}
			switch kind {
			case "record":
				delete(f.records, resolvKey(s))
			case "exclusive":
				f.exclusive = append(f.exclusive, "other.vpn")
			case "file":
				f.resolver = "nameserver 192.0.2.99\n"
			case "index":
				owned = func(Spec) error { return ErrGone }
			}
			if c.Matches(context.Background(), owned, s) {
				t.Fatal("change ignored")
			}
		})
	}
}
func TestOpenResolvRefusesUnmanagedResolverBeforeMutation(t *testing.T) {
	f, c := newResolvFake()
	f.resolver = "# managed by another service\nnameserver 192.0.2.1\n"
	if err := c.Apply(context.Background(), func(Spec) error { return nil }, resolvSpec()); err != ErrUnavailable || len(f.writes) != 0 {
		t.Fatal(err, f.writes)
	}
}
func TestOpenResolvVersionAndAddressParsing(t *testing.T) {
	for _, v := range []string{"openresolv 3.17.4\nCopyright", "openresolv 3.18.0\n"} {
		if !supportedOpenResolv(v) {
			t.Fatal(v)
		}
	}
	for _, v := range []string{"resolvconf 1.2", "systemd 260", "openresolv 3.17.3", "openresolv 4.0.0", "openresolv 3.17.4;evil", "openresolv 3.17.-4"} {
		if supportedOpenResolv(v) {
			t.Fatal(v)
		}
	}
	got, err := resolverAddresses("# header\nsearch test\nnameserver 172.19.0.2 # own\nnameserver fdfe:dcba:9876::2\noptions edns0\n")
	if err != nil || !slices.Equal(got, resolvSpec().Servers) {
		t.Fatal(got, err)
	}
	for _, v := range []string{"nameserver abc", "nameserver 1.1.1.1 other", "nameserver ::ffff:1.1.1.1", strings.Repeat("x", 65537), "nameserver 1.1.1.1\x00"} {
		if _, e := resolverAddresses(v); e == nil {
			t.Fatal("invalid accepted")
		}
	}
}
