//go:build linux

package tunsession

import (
	"bufio"
	"bytes"
	"os"
	"os/exec"
	"strings"
	"syscall"
	"testing"

	"golang.org/x/sys/unix"
)

func TestPrivateResolverViewNamespace(t *testing.T) {
	if os.Getenv("THRONIUM_OPENRESOLV_PRIVATE_FIXTURE") != "1" {
		t.Skip("requires owned root, PID and mount namespaces")
	}
	original := os.Getenv("THRONIUM_TEST_ORIGINAL_MNTNS")
	current, err := os.Readlink("/proc/self/ns/mnt")
	if err != nil || original == "" || original == current || os.Geteuid() != 0 {
		t.Fatal("host forbidden")
	}
	if err = os.Mkdir("/run/thronium-tun", 0700); err != nil {
		t.Fatal(err)
	}
	first := []byte("# Generated by resolvconf\nsearch first.test\nnameserver 192.0.2.53\n")
	next := []byte("# Generated by resolvconf\nsearch next.test\nnameserver 198.51.100.53\n")
	for _, uid := range []uint32{0, 1000} {
		if err = os.WriteFile("/etc/resolv.conf", first, 0644); err != nil {
			t.Fatal(err)
		}
		command := exec.Command("/bin/sh", "-c", `cat /etc/resolv.conf; readlink /proc/self/ns/mnt; echo READY; read done; cat /etc/resolv.conf; if echo wrong > /etc/resolv.conf 2>/dev/null; then exit 70; fi; exit 0`)
		command.SysProcAttr = &syscall.SysProcAttr{Credential: &syscall.Credential{Uid: uid, Gid: uid, Groups: []uint32{uid}}, AmbientCaps: []uintptr{unix.CAP_NET_ADMIN, unix.CAP_NET_RAW}}
		stdout, err := command.StdoutPipe()
		if err != nil {
			t.Fatal(err)
		}
		stdin, err := command.StdinPipe()
		if err != nil {
			t.Fatal(err)
		}
		if err = startWithResolverView(command); err != nil {
			t.Fatal("start", uid, err)
		}
		defer command.Process.Kill()
		reader := bufio.NewScanner(stdout)
		var lines []string
		for reader.Scan() {
			if reader.Text() == "READY" {
				break
			}
			lines = append(lines, reader.Text())
		}
		if len(lines) != 4 || strings.Join(lines[:3], "\n")+"\n" != string(first) || lines[3] == current {
			t.Fatal("worker view or namespace", lines)
		}
		body, err := os.ReadFile("/etc/resolv.conf")
		if err != nil || !bytes.Equal(body, first) {
			t.Fatal("parent resolver changed")
		}
		if err = os.WriteFile("/etc/resolv.conf", next, 0644); err != nil {
			t.Fatal(err)
		}
		if _, err = stdin.Write([]byte("continue\n")); err != nil {
			t.Fatal(err)
		}
		stdin.Close()
		lines = nil
		for reader.Scan() {
			lines = append(lines, reader.Text())
		}
		if err = command.Wait(); err != nil {
			t.Fatal("worker could write resolver or failed", uid, err)
		}
		if strings.Join(lines, "\n")+"\n" != string(first) {
			t.Fatal("worker adopted own TUN resolver", lines)
		}
		after, _ := os.Readlink("/proc/self/ns/mnt")
		body, err = os.ReadFile("/etc/resolv.conf")
		if err != nil || after != current || !bytes.Equal(body, next) {
			t.Fatal("parent view not preserved", uid, after, current, string(body), err)
		}
		// A separate connection sees the latest physical network DNS.
		fresh := exec.Command("/bin/cat", "/etc/resolv.conf")
		var output bytes.Buffer
		fresh.Stdout = &output
		if err = startWithResolverView(fresh); err != nil {
			t.Fatal(err)
		}
		if err = fresh.Wait(); err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(output.Bytes(), next) {
			t.Fatal("reconnect retained stale resolver")
		}
	}
	missing := exec.Command("/run/thronium-no-such-executable")
	if err = startWithResolverView(missing); err == nil {
		t.Fatal("missing executable started")
	}
	entries, err := os.ReadDir("/run/thronium-tun")
	if err != nil || len(entries) != 0 {
		t.Fatal("source file leaked", err, len(entries))
	}
	after, _ := os.Readlink("/proc/self/ns/mnt")
	if after != current {
		t.Fatal("failure changed parent namespace")
	}
}
