import { b, f, json, list, n, secret, select, type Field } from './schemaFields.ts';

// OpenVPN and OpenConnect forms (sing-box option/openvpn.go, option/openconnect.go).
// Endpoint UDP NAT behaviour shared with WireGuard (option/wireguard.go).
const udpNatBehaviors = ['', 'endpoint_independent', 'address_dependent', 'address_and_port_dependent'];
export const udpNatFields: Field[] = [
  select('udp_mapping', 'profiles.udp_mapping', udpNatBehaviors),
  select('udp_filtering', 'profiles.udp_filtering', udpNatBehaviors),
  n('udp_nat_max', 'profiles.udp_nat_max', 0, 4294967295),
];
const tlsVersions = ['1.0', '1.1', '1.2', '1.3'];
// The pinned core rejects an EKU next to `remote_certificate_tls`; say so on the field.
const remoteCertificateEku: Field = {
  ...f('tls.remote_certificate_eku', 'profiles.remote_certificate_eku'),
  hint: 'profiles.remote_certificate_eku_hint',
};
export const vpnTLS = (openconnect: boolean): Field[] => [
  f('tls.server_name', 'profiles.server_name_a18c912'),
  ...(openconnect
    ? [
        b('tls.insecure', 'profiles.skip_certificate_verification_a559e43'),
        b('tls.system_trust_disabled', 'profiles.disable_system_trust_store_1f9153b'),
      ]
    : [
        select('tls.server_name_type', 'profiles.server_name_match_d16696a', [
          'subject',
          'name',
          'name-prefix',
        ]),
        select('tls.remote_certificate_tls', 'profiles.remote_certificate_role_7a86a08', [
          'server',
          'client',
          'none',
        ]),
      ]),
  list(
    'tls.' + (openconnect ? 'certificate_authority' : 'certificate'),
    'profiles.ca_certificate_pem_0c71ee8',
  ),
  f(
    'tls.' + (openconnect ? 'certificate_authority_path' : 'certificate_path'),
    'profiles.ca_certificate_file_ca0c290',
  ),
  list('tls.client_certificate', 'profiles.client_certificate_pem_5fe95b4'),
  f('tls.client_certificate_path', 'profiles.client_certificate_file_6c02a18'),
  list('tls.client_key', 'profiles.client_key_pem_a908781'),
  f('tls.client_key_path', 'profiles.client_key_file_fc19886'),
  list('tls.peer_fingerprint', 'profiles.peer_fingerprints_e7036f7'),
  ...(openconnect
    ? [
        secret('tls.client_key_password', 'profiles.client_key_password_06dff4e'),
        list('tls.mca_certificate', 'profiles.mca_certificate'),
        f('tls.mca_certificate_path', 'profiles.mca_certificate_path'),
        list('tls.mca_key', 'profiles.mca_key'),
        f('tls.mca_key_path', 'profiles.mca_key_path'),
        secret('tls.mca_key_password', 'profiles.mca_key_password'),
      ]
    : [
        select('tls.control_wrap.type', 'profiles.control_channel_protection_b63df76', [
          'tls_auth',
          'tls_crypt',
          'tls_crypt_v2',
        ]),
        list('tls.control_wrap.key', 'profiles.control_channel_key_9af5ead'),
        f('tls.control_wrap.key_path', 'profiles.control_channel_key_file_341402d'),
        select('tls.control_wrap.direction', 'profiles.key_direction_b37eaf8', ['client', 'server']),
        f('tls.crl_path', 'profiles.crl_path'),
        list('tls.remote_certificate_ku', 'profiles.remote_certificate_ku'),
        remoteCertificateEku,
        select('tls.certificate_profile', 'profiles.certificate_profile', [
          'legacy',
          'preferred',
          'insecure',
          'suiteb',
        ]),
        select('tls.ns_certificate_type', 'profiles.ns_certificate_type', ['server', 'client']),
        select('tls.version_min', 'profiles.minimum_tls_version_53a3c25', tlsVersions),
        select('tls.version_max', 'profiles.maximum_tls_version_35da107', tlsVersions),
        f('tls.cipher', 'profiles.tls_cipher'),
        f('tls.groups', 'profiles.tls_groups'),
      ]),
];
export const openvpnAdvanced: Field[] = [
  json('servers', 'profiles.alternative_servers_8df98e4'),
  b('remote_random', 'profiles.randomize_server_order_fe19896'),
  list('address', 'profiles.tunnel_addresses_cidr_82cd48a'),
  f('peer_address', 'profiles.peer_ipv4_f250ea4'),
  f('peer_address_ipv6', 'profiles.peer_ipv6_4b80b3a'),
  select('topology', 'profiles.topology_ba28bcf', ['net30', 'p2p', 'subnet']),
  list('static_key', 'profiles.static_key_8fa04f2'),
  f('static_key_path', 'profiles.static_key_file_32f7bb6'),
  select('key_direction', 'profiles.key_direction_b37eaf8', ['client', 'server']),
  f('cipher', 'profiles.cipher_494ca3d'),
  list('data_ciphers', 'profiles.data_ciphers_f497069'),
  f('data_ciphers_fallback', 'profiles.fallback_cipher_262b71d'),
  f('auth', 'profiles.authentication_digest_1e08e9c'),
  n('mss_fix', 'profiles.mss_fix_536ee1d'),
  b('mss_fix_disabled', 'profiles.disable_mss_fix_77d66a0'),
  select('mss_fix_mode', 'profiles.mss_fix_mode_a20a910', ['mtu', 'fixed']),
  n('fragment', 'profiles.fragment_size_17c4872'),
  n('replay_window', 'profiles.replay_window_30d8008'),
  f('replay_window_time', 'profiles.replay_window_time_e46aad1'),
  select('compression', 'profiles.compression_a542b30', [
    'none',
    'no',
    'lz4',
    'lz4-v2',
    'stub',
    'stub-v2',
    'disabled',
    'off',
  ]),
  select('compression_lzo', 'profiles.compression_lzo', [
    'none',
    'no',
    'yes',
    'adaptive',
    'asym',
    'disabled',
    'off',
  ]),
  select('allow_compression', 'profiles.allow_compression_07af5bd', ['no', 'asym', 'yes']),
  b('route_no_pull', 'profiles.ignore_pushed_routes_ec9c647'),
  json('pull_filters', 'profiles.pull_filters_4ee6c93'),
  list('routes', 'profiles.routes_3dee073'),
  f('route_gateway', 'profiles.route_gateway_7cbcff3'),
  n('route_metric', 'profiles.route_metric_52c34f5'),
  b('redirect_gateway', 'profiles.redirect_gateway_7aff6b2'),
  list('redirect_gateway_flags', 'profiles.redirect_gateway_flags_587b561'),
  b('redirect_private', 'profiles.redirect_private_networks_5f4c317'),
  b('block_ipv6', 'profiles.block_ipv6_0838eee'),
  f('ping_interval', 'profiles.ping_interval_25ea3c3'),
  f('ping_restart', 'profiles.ping_restart_8cb1576'),
  b('ping_restart_disabled', 'profiles.disable_ping_restart_064fe15'),
  f('renegotiate_interval', 'profiles.renegotiation_interval_baa6ad6'),
  b('renegotiate_disabled', 'profiles.disable_renegotiation_ee28d10'),
  n('renegotiate_bytes', 'profiles.renegotiate_after_bytes_924a7cd'),
  n('renegotiate_packets', 'profiles.renegotiate_after_packets_5dc5d85'),
  f('tls_timeout', 'profiles.tls_timeout_b603f6a'),
  f('handshake_window', 'profiles.handshake_window_8b0d5c6'),
  n('explicit_exit_notify', 'profiles.exit_notifications_6214fa0'),
  b('system', 'profiles.system_interface_b778c71'),
  f('name', 'profiles.interface_name_d39d347'),
  n('mtu', 'profiles.mtu_aeb4832'),
  f('udp_timeout', 'profiles.udp_timeout_846623f'),
  ...udpNatFields,
];
export const openconnectAdvanced: Field[] = [
  f('reported_os', 'profiles.reported_operating_system_a2a0903'),
  f('user_agent', 'profiles.user_agent_755f806'),
  f('version', 'profiles.client_version_3ec77ea'),
  f('local_hostname', 'profiles.local_hostname_547e03b'),
  select('token.mode', 'profiles.token_mode_607be12', ['totp', 'hotp', 'stoken', 'oidc']),
  secret('token.secret', 'profiles.token_secret_0da41f1'),
  f('token.secret_path', 'profiles.token_secret_file_83a239b'),
  secret('token.pin', 'profiles.token_pin_861a684'),
  secret('token.password', 'profiles.token_password_ad8ce52'),
  n('token.counter', 'profiles.token_counter_56b438e'),
  f('token.device_id', 'profiles.token_device_id_a98c51b'),
  b('no_udp', 'profiles.disable_udp_f522e15'),
  n('dtls_local_port', 'profiles.local_dtls_port_0f40051', 0, 65535),
  b('compression_disabled', 'profiles.disable_compression_ea7529b'),
  select('compression_mode', 'profiles.compression_mode_f0106bf', ['stateless', 'all']),
  b('ipv6_disabled', 'profiles.disable_ipv6_258fd5b'),
  b('http_keepalive_disabled', 'profiles.disable_http_keepalive_568c9c9'),
  b('xml_post_disabled', 'profiles.disable_xml_post_7c908bc'),
  b('external_auth_disabled', 'profiles.disable_external_authentication_e9b4d58'),
  b('password_authentication_disabled', 'profiles.disable_password_authentication_85eb927'),
  b('tcp_keep_alive_enabled', 'profiles.tcp_keepalive_cb40da3'),
  b('pfs', 'profiles.perfect_forward_secrecy_24be66d'),
  n('mtu', 'profiles.mtu_aeb4832'),
  n('base_mtu', 'profiles.base_mtu_113af81'),
  f('dpd_interval', 'profiles.dpd_interval_b406a7e'),
  f('reconnect_timeout', 'profiles.reconnect_timeout_57e89f9'),
  f('trojan_interval', 'profiles.host_check_interval_cfe83e2'),
  n('queue_length', 'profiles.queue_length_ad615bb'),
  b('allow_insecure_crypto', 'profiles.allow_insecure_cryptography_71105b0'),
  json('mobile', 'profiles.mobile_device_information_92ed856'),
  json('csd', 'profiles.csd_1865b92'),
  json('hip', 'profiles.hip_1f5f185'),
  json('tncc', 'profiles.tncc_378b87c'),
  json('fortinet_host_check', 'profiles.fortinet_host_check_9bc62a0'),
  json('form_entries', 'profiles.saved_form_answers_9ab9341'),
  b('system', 'profiles.system_interface_b778c71'),
  f('name', 'profiles.interface_name_d39d347'),
  f('udp_timeout', 'profiles.udp_timeout_846623f'),
  ...udpNatFields,
];
